# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcGMM_REGRESSION(wx.Frame):
#!XRCED:begin-block:xrcGMM_REGRESSION.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcGMM_REGRESSION.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "GMM_REGRESSION")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.RegressionToolBar = xrc.XRCCTRL(self, "RegressionToolBar")
        self.scroll = xrc.XRCCTRL(self, "scroll")
        self.Panel = xrc.XRCCTRL(self, "Panel")
        self.DATAFILE = xrc.XRCCTRL(self, "DATAFILE")
        self.DATA_INPUTFILE = xrc.XRCCTRL(self, "DATA_INPUTFILE")
        self.Panel_Weights = xrc.XRCCTRL(self, "Panel_Weights")
        self.CreateMWeightsButton = xrc.XRCCTRL(self, "CreateMWeightsButton")
        self.OpenMWeightsButton = xrc.XRCCTRL(self, "OpenMWeightsButton")
        self.MWeights_ListBox = xrc.XRCCTRL(self, "MWeights_ListBox")
        self.CreateKWeightsButton = xrc.XRCCTRL(self, "CreateKWeightsButton")
        self.OpenKWeightsButton = xrc.XRCCTRL(self, "OpenKWeightsButton")
        self.KWeights_ListBox = xrc.XRCCTRL(self, "KWeights_ListBox")
        self.Panel_Spec = xrc.XRCCTRL(self, "Panel_Spec")
        self.Y_TextCtrl = xrc.XRCCTRL(self, "Y_TextCtrl")
        self.YE_ListBox = xrc.XRCCTRL(self, "YE_ListBox")
        self.H_ListBox = xrc.XRCCTRL(self, "H_ListBox")
        self.R_TextCtrl = xrc.XRCCTRL(self, "R_TextCtrl")
        self.S_TextCtrl = xrc.XRCCTRL(self, "S_TextCtrl")
        self.T_TextCtrl = xrc.XRCCTRL(self, "T_TextCtrl")
        self.X_ListBox = xrc.XRCCTRL(self, "X_ListBox")
        self.Panel_Estimation = xrc.XRCCTRL(self, "Panel_Estimation")
        self.MT_STD = xrc.XRCCTRL(self, "MT_STD")
        self.MT_LAG = xrc.XRCCTRL(self, "MT_LAG")
        self.MT_ERR = xrc.XRCCTRL(self, "MT_ERR")
        self.MT_LAGERR = xrc.XRCCTRL(self, "MT_LAGERR")
        self.ENDO_CHECK = xrc.XRCCTRL(self, "ENDO_CHECK")
        self.ST_LM = xrc.XRCCTRL(self, "ST_LM")
        self.SEWhiteCheckBox = xrc.XRCCTRL(self, "SEWhiteCheckBox")
        self.SEHACCheckBox = xrc.XRCCTRL(self, "SEHACCheckBox")
        self.SEHETCheckBox = xrc.XRCCTRL(self, "SEHETCheckBox")
        self.RunButton = xrc.XRCCTRL(self, "RunButton")
        self.SaveButton = xrc.XRCCTRL(self, "SaveButton")
        self.CloseButton = xrc.XRCCTRL(self, "CloseButton")



class xrcTextWindow(wx.Frame):
#!XRCED:begin-block:xrcTextWindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcTextWindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "TextWindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.ToolBar = xrc.XRCCTRL(self, "ToolBar")
        self.Panel = xrc.XRCCTRL(self, "Panel")
        self.Text = xrc.XRCCTRL(self, "Text")



class xrcVariablePanel(wx.Panel):
#!XRCED:begin-block:xrcVariablePanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcVariablePanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "VariablePanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.ToolBar = xrc.XRCCTRL(self, "ToolBar")
        self.variableList = xrc.XRCCTRL(self, "variableList")



class xrcweightsContextMenu(wx.Menu):
    def __init__(self):
        pre = get_resources().LoadMenu("weightsContextMenu")

        # This is a copy of Robin's PostCreate voodoo magic in wx.Window that
        # relinks the self object with the menu object.
        self.this = pre.this
        self.thisown = pre.thisown
        pre.thisown = 0
        if hasattr(self, '_setOORInfo'):
            self._setOORInfo(self)

        # Define variables for the menu items





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    OGRegression_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="GMM_REGRESSION">
    <title>GeoDaSpace Regression</title>
    <centered>1</centered>
    <size>570,650</size>
    <style>wxCAPTION|wxSYSTEM_MENU|wxRESIZE_BORDER|wxRESIZE_BOX|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX</style>
    <object class="wxToolBar" name="RegressionToolBar">
      <object class="tool" name="ToolNewModel">
        <bitmap stock_id="wxART_NEW"/>
        <tooltip>Create New Model: Choose dbf File</tooltip>
        <longhelp>Click to create a new model.</longhelp>
      </object>
      <object class="tool" name="ToolOpenModel">
        <bitmap stock_id="wxART_FILE_OPEN"/>
        <tooltip>Open Existing Model: Choose .mdl File</tooltip>
      </object>
      <object class="tool" name="ToolSaveModel">
        <bitmap stock_id="wxART_FILE_SAVE"/>
        <tooltip>Save Model...</tooltip>
      </object>
      <object class="tool" name="ToolSaveModelAs">
        <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        <tooltip>Save Model As...</tooltip>
      </object>
      <object class="separator"/>
      <object class="tool" name="ToolVariableSelector">
        <bitmap stock_id="wxART_REPORT_VIEW"/>
        <tooltip>Open the Variable List</tooltip>
      </object>
      <object class="tool" name="ToolResultsWindow">
        <bitmap stock_id="wxART_HELP_PAGE"/>
        <tooltip>Show the Results Window</tooltip>
      </object>
      <object class="separator"/>
      <object class="tool" name="ToolAdvanced">
        <bitmap>gear_png</bitmap>
        <tooltip>Show Advanced Settings</tooltip>
      </object>
      <style>wxTB_FLAT|wxTB_HORIZONTAL</style>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="wxScrolledWindow" name="scroll">
      <object class="wxBoxSizer">
        <orient>wxVERTICAL</orient>
        <object class="sizeritem">
          <object class="wxPanel" name="Panel">
            <object class="wxBoxSizer">
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <orient>wxHORIZONTAL</orient>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxVERTICAL</orient>
                      <object class="sizeritem">
                        <object class="wxStaticBoxSizer">
                          <object class="sizeritem">
                            <object class="wxBoxSizer">
                              <orient>wxHORIZONTAL</orient>
                              <object class="sizeritem">
                                <object class="wxTextCtrl" name="DATAFILE">
                                  <size>75,-1d</size>
                                  <style>wxTE_READONLY</style>
                                  <XRCED>
                                    <assign_var>1</assign_var>
                                  </XRCED>
                                </object>
                                <flag>wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL</flag>
                                <border>1</border>
                              </object>
                              <object class="sizeritem">
                                <object class="wxBitmapButton" name="DATA_INPUTFILE">
                                  <size>15,13d</size>
                                  <bitmap stock_id="wxART_FILE_OPEN"/>
                                  <tooltip>Open dbf File...</tooltip>
                                  <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                                  <XRCED>
                                    <assign_var>1</assign_var>
                                  </XRCED>
                                </object>
                                <flag>wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL</flag>
                                <border>5</border>
                              </object>
                            </object>
                          </object>
                          <label>Data File</label>
                          <orient>wxVERTICAL</orient>
                        </object>
                        <flag>wxALL|wxALIGN_CENTRE|wxADJUST_MINSIZE</flag>
                        <border>3</border>
                      </object>
                      <object class="sizeritem">
                        <object class="wxPanel" name="Panel_Weights">
                          <object class="wxBoxSizer">
                            <orient>wxVERTICAL</orient>
                            <object class="sizeritem">
                              <object class="wxStaticBoxSizer">
                                <orient>wxVERTICAL</orient>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <orient>wxHORIZONTAL</orient>
                                    <object class="sizeritem">
                                      <object class="wxBitmapButton" name="CreateMWeightsButton">
                                        <size>15,13d</size>
                                        <bitmap stock_id="wxART_NEW"/>
                                        <tooltip>Create Weights</tooltip>
                                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBitmapButton" name="OpenMWeightsButton">
                                        <size>15,13d</size>
                                        <bitmap stock_id="wxART_FILE_OPEN"/>
                                        <tooltip>Open Weights</tooltip>
                                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                                    </object>
                                  </object>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxCheckListBox" name="MWeights_ListBox">
                                    <tooltip>Model Weights</tooltip>
                                    <style>wxLB_HSCROLL</style>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxADJUST_MINSIZE</flag>
                                </object>
                                <label>Model Weights</label>
                              </object>
                              <option>1</option>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                            <object class="sizeritem">
                              <object class="wxStaticBoxSizer">
                                <orient>wxVERTICAL</orient>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <orient>wxHORIZONTAL</orient>
                                    <object class="sizeritem">
                                      <object class="wxBitmapButton" name="CreateKWeightsButton">
                                        <size>15,13d</size>
                                        <bitmap stock_id="wxART_NEW"/>
                                        <tooltip>Create Weights</tooltip>
                                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBitmapButton" name="OpenKWeightsButton">
                                        <size>15,13d</size>
                                        <bitmap stock_id="wxART_FILE_OPEN"/>
                                        <tooltip>Open Weights</tooltip>
                                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                                    </object>
                                  </object>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxCheckListBox" name="KWeights_ListBox">
                                    <tooltip>Kernel Weights</tooltip>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxADJUST_MINSIZE</flag>
                                </object>
                                <label>Kernel Weights</label>
                              </object>
                              <option>1</option>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <option>1</option>
                        <flag>wxALL|wxEXPAND</flag>
                        <border>3</border>
                      </object>
                    </object>
                    <flag>wxALL|wxEXPAND|wxGROW</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxVERTICAL</orient>
                      <object class="sizeritem">
                        <object class="wxPanel" name="Panel_Spec">
                          <object class="wxStaticBoxSizer">
                            <label>Specification</label>
                            <orient>wxHORIZONTAL</orient>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>Y</label>
                                    <tooltip>Dependent Variable</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="Y_TextCtrl">
                                    <tooltip>Dependent Variable</tooltip>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>YE</label>
                                    <tooltip>Endogenous Variables</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxListBox" name="YE_ListBox">
                                    <tooltip>Endogenous Variables</tooltip>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>H</label>
                                    <tooltip>Instruments</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxListBox" name="H_ListBox">
                                    <tooltip>Instruments</tooltip>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>R</label>
                                    <hidden>1</hidden>
                                    <tooltip>Regime (Coming Soon)</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="R_TextCtrl">
                                    <tooltip>Regime (Coming Soon)</tooltip>
                                    <hidden>1</hidden>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>S</label>
                                    <hidden>1</hidden>
                                    <tooltip>Space (Coming Soon)</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="S_TextCtrl">
                                    <tooltip>Space (Coming Soon)</tooltip>
                                    <hidden>1</hidden>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>T</label>
                                    <hidden>1</hidden>
                                    <tooltip>Time (Coming Soon)</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="T_TextCtrl">
                                    <tooltip>Time (Coming Soon)</tooltip>
                                    <hidden>1</hidden>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <orient>wxVERTICAL</orient>
                              </object>
                              <option>6</option>
                              <flag>wxALL|wxEXPAND|wxGROW|wxADJUST_MINSIZE</flag>
                              <border>3</border>
                            </object>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxVERTICAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>X</label>
                                    <tooltip>Independent Variables</tooltip>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxListBox" name="X_ListBox">
                                    <tooltip>Independent Variables</tooltip>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                                  <border>-3</border>
                                </object>
                              </object>
                              <option>8</option>
                              <flag>wxALL|wxEXPAND|wxGROW|wxADJUST_MINSIZE</flag>
                              <border>3</border>
                            </object>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <option>1</option>
                        <flag>wxALL|wxEXPAND</flag>
                        <border>3</border>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxALL|wxEXPAND|wxGROW</flag>
                  </object>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND|wxGROW</flag>
              </object>
              <object class="sizeritem">
                <object class="wxPanel" name="Panel_Estimation">
                  <object class="wxBoxSizer">
                    <orient>wxHORIZONTAL</orient>
                    <object class="sizeritem">
                      <object class="wxStaticBoxSizer">
                        <orient>wxVERTICAL</orient>
                        <object class="sizeritem">
                          <object class="wxBoxSizer">
                            <orient>wxHORIZONTAL</orient>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxVERTICAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticBoxSizer">
                                    <label>Model Type</label>
                                    <orient>wxVERTICAL</orient>
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="MT_STD">
                                        <label>Standard</label>
                                        <value>1</value>
                                        <tooltip>Estimates Standard OLS Model (No Space)</tooltip>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP</flag>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="MT_LAG">
                                        <label>Spatial Lag</label>
                                        <tooltip>Estimated using S2SLS -Kelejian, H. and Prucha, I., (1998), Journal of Real Estate, Finance and Economics</tooltip>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP|wxEXPAND</flag>
                                      <border>4</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="MT_ERR">
                                        <label>Spatial Error</label>
                                        <tooltip>Estimated using GM estimator -Kelejian, H. and Prucha, I., (1999), International Economic Review</tooltip>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP</flag>
                                      <border>4</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="MT_LAGERR">
                                        <label>Spatial Lag+Error</label>
                                        <tooltip>Estimated using GM estimator -Kelejian, H. and Prucha, I., (1999), International Economic Review</tooltip>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP</flag>
                                      <border>4</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxCheckBox" name="ENDO_CHECK">
                                        <label>Endogeneity</label>
                                        <tooltip>Choose this option if you have additional endogenous variables within your set of explanatory variables. Drag your additional endogenous variables to the box labeled YE. Instruments for these variables should be defined in the box labeled H.</tooltip>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP</flag>
                                      <border>12</border>
                                    </object>
                                  </object>
                                  <option>1</option>
                                  <flag>wxBOTTOM|wxLEFT|wxRIGHT|wxGROW</flag>
                                  <border>3</border>
                                </object>
                              </object>
                              <option>1</option>
                              <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE|wxADJUST_MINSIZE</flag>
                            </object>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxVERTICAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticBoxSizer">
                                    <label>Spatial Tests</label>
                                    <orient>wxVERTICAL</orient>
                                    <object class="sizeritem">
                                      <object class="wxCheckBox" name="ST_LM">
                                        <label>LM</label>
                                        <tooltip>Lagrange Multiplier Tests for Spatial Autocorrelation, (see Anselin et al. 1996, Regional Science and Urban Economics)</tooltip>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                    </object>
                                  </object>
                                  <flag>wxLEFT|wxRIGHT|wxEXPAND</flag>
                                  <border>3</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxStaticBoxSizer">
                                    <label>Standard Errors</label>
                                    <orient>wxVERTICAL</orient>
                                    <object class="sizeritem">
                                      <object class="wxCheckBox" name="SEWhiteCheckBox">
                                        <label>White</label>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP|wxBOTTOM|wxALIGN_LEFT</flag>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxCheckBox" name="SEHACCheckBox">
                                        <label>HAC</label>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP|wxBOTTOM|wxALIGN_LEFT</flag>
                                      <border>3</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxCheckBox" name="SEHETCheckBox">
                                        <label>KP HET</label>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxTOP|wxBOTTOM|wxALIGN_LEFT</flag>
                                    </object>
                                  </object>
                                  <option>1</option>
                                  <flag>wxBOTTOM|wxLEFT|wxRIGHT|wxEXPAND</flag>
                                  <border>3</border>
                                </object>
                              </object>
                              <option>1</option>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE</flag>
                        </object>
                        <object class="sizeritem">
                          <flag>wxALIGN_CENTER_HORIZONTAL|wxALL</flag>
                          <border>2</border>
                          <object class="wxBoxSizer">
                            <orient>wxHORIZONTAL</orient>
                            <object class="sizeritem">
                              <object class="wxButton" name="RunButton">
                                <label>Run</label>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>2</border>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="sizeritem">
                              <object class="wxButton" name="SaveButton">
                                <label>&amp;Sa&amp;ve</label>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>2</border>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="spacer">
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>5</border>
                              <size>5,5d</size>
                            </object>
                            <object class="sizeritem">
                              <object class="wxButton" name="CloseButton">
                                <label>Close</label>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALIGN_CENTER_VERTICAL|wxALL</flag>
                              <border>2</border>
                            </object>
                          </object>
                        </object>
                        <label>Model Estimation</label>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_CENTRE</flag>
                    </object>
                  </object>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND|wxGROW</flag>
                <border>3</border>
              </object>
            </object>
            <size>570,650</size>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <option>1</option>
          <flag>wxALL|wxEXPAND</flag>
        </object>
      </object>
      <style>wxHSCROLL|wxVSCROLL</style>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <bg>#E8E8E8</bg>
  </object>
  <object class="wxFrame" name="TextWindow">
    <title>Results</title>
    <object class="wxToolBar" name="ToolBar">
      <object class="tool" name="ToolNew">
        <bitmap stock_id="wxART_NEW"/>
        <tooltip>Create A New Results File...</tooltip>
      </object>
      <object class="tool" name="ToolOpen">
        <bitmap stock_id="wxART_FILE_OPEN"/>
        <tooltip>Open Results File...</tooltip>
      </object>
      <object class="tool" name="ToolSave">
        <bitmap stock_id="wxART_FILE_SAVE"/>
        <tooltip>Save Results File</tooltip>
      </object>
      <object class="tool" name="ToolSaveAs">
        <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        <tooltip>Save Results File As...</tooltip>
      </object>
      <object class="separator"/>
      <object class="tool" name="ToolFontSmaller">
        <bitmap>list_remove_png</bitmap>
        <tooltip>Decrease Font Size</tooltip>
        <label>TOOL</label>
      </object>
      <object class="tool" name="ToolFontBigger">
        <bitmap>list_add_png</bitmap>
        <tooltip>Increase Font Size</tooltip>
        <label>TOOL</label>
      </object>
      <style>wxTB_FLAT|wxTB_HORIZONTAL</style>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxPanel" name="Panel">
          <object class="wxBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxTextCtrl" name="Text">
                <size>700,300</size>
                <font>
                  <size>10</size>
                  <style>normal</style>
                  <weight>normal</weight>
                  <underlined>0</underlined>
                  <family>default</family>
                  <face>Courier New</face>
                </font>
                <style>wxTE_MULTILINE|wxTE_READONLY|wxTE_LINEWRAP</style>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>1</option>
              <flag>wxALL|wxEXPAND|wxADJUST_MINSIZE</flag>
            </object>
          </object>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
      </object>
    </object>
  </object>
  <object class="wxPanel" name="VariablePanel">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxToolBar" name="ToolBar">
          <object class="tool" name="ToolSpatialLag">
            <bitmap>W__png</bitmap>
            <tooltip>Create A Spatial Lag of the Selected Variables...</tooltip>
          </object>
          <object class="separator"/>
          <bitmapsize>15,15</bitmapsize>
          <margins>0,5</margins>
          <style>wxTB_FLAT|wxTB_HORIZONTAL</style>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <flag>wxALL|wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Variables</label>
                </object>
              </object>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxListCtrl" name="variableList">
              <style>wxLC_REPORT|wxLC_NO_HEADER|wxLC_HRULES</style>
              <XRCED>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <option>1</option>
            <flag>wxBOTTOM|wxEXPAND|wxGROW|wxSTRETCH_NOT|wxADJUST_MINSIZE</flag>
            <border>5</border>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
      </object>
    </object>
  </object>
  <object class="wxMenu" name="weightsContextMenu">
    <label>Weights</label>
    <object class="wxMenuItem">
      <label>Model Weights</label>
      <radio>1</radio>
    </object>
    <object class="wxMenuItem">
      <label>Kernal Weights</label>
      <radio>1</radio>
    </object>
    <object class="separator"/>
    <object class="wxMenuItem">
      <label>MENUITEM</label>
      <radio>1</radio>
    </object>
    <object class="wxMenuItem">
      <label>MENUITEM</label>
      <radio>1</radio>
    </object>
  </object>
</resource>'''

    gear_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x18\x00\x00\x00\x18\x08\x06\x00\x00\x00\
\xe0w=\xf8\x00\x00\x04\xd9iCCPICC Profile\x00\x00x\x01\xe5\x96{LSg\x18\xc6\
\x9fsz\x07*-\xd4"S\xb4:\x86\xc8
\xeb\x00e\x15B\x04\xc6\x18\x88\x80\x80"\x8et\xb6\xa5B\x95Bs\xa8\x08\xb2\
\xa9\x0c2\x98\x17\xbc\xc0T\x166\x94\xa0x\xc9\xe6\x82\xe2\x1c\xc3ycB4q\x88\
\x192\x9cS\xac\xc6\x1b\xe2m\x90\x80h\xf7\x9d6\x1bY\x0c\xc9\xfe\xf7\xfb\xe7\
\xfd}\xefy\xce\xfb\xe5=\xe7<\xdfw\x00\xe1Q\xad\xd9\x9cC\x030\xe5Z\x98\xe4\
\x98H\xc5\x92\xf4\xa5
A7\xf8\x10B\x06w\xb8k\xf5\xf9\xe6\x88\xa4\xa4x"\x19g\x0cu\x83b/]\xf6gk\
\x8d#\x1a/-f\xc8\x82\x00\xa5 \x02Y\x96\x83\x83Y\xd69\xf8C\x96W[\xcc\x16\
\xa2\xc9`Y\x9f\xad\xcd$l&\xacdR\x93\xa3\x08\xd7\x12\x1e\xcd\xb23\xbd\x8b\
e\x9d\x9d9\xd5,\x17\xe8\xb3\xc8\xbd\xdc\xad\x84U\xb9\x99\xc6\\\xc2\xa7\x00\
\xce\x84LC\xbe\x1e\x10t\x92\xfc\x06\xbd\x99!\x1a![\xdf\xdfd\xca#\xf5\x85\
\x9b\x08\xfb\xb2\xcf\x82D2\xf2\xca\x00\xf5\x01\x80\xf6\x1a\xcb-#\xf9\xef\
\xb3\x00\xf9\xa3\xb1\xdc\xccd2\xf7\x00Z\xe4c\xb9g\xd3\xec\xcf\x87z\xef\x87\
\xfc\xe5A\x81l5P\xd2\x16\xb2\x86\xb7\xcd6P\x038U\x02/\xe6\xdal#R\x9bm\xb4\
\x0b\xe0)\x81CS\xf5\xab\x98\x02\xbb\x16($\x91\x03\x27x`\x16"\xa0A\x09\x0e\
\xa2\x97\x92R\x89T5\xd5G\x87\xd0;\xe8\x97\x1c3\xa7\x9f\xcb\xf0\xb8\xbc=\
\xfcX\xfeK\xc1I\xe1&\x91\xc1)\xce9\xcce\xae8jB\x9ak\x81\xa4^\xfa\xd0}\x89\
\xec\x86\xbcd\xd2\x1c\xcf\xe1\xc9m^[\xa6%M\xe7\xceh\xf5.\xf6\x89\xf4u\x9d\
u\xeb\xed\xd3\xfe\xfb\xde\xa9z\xb7"\xa8|ve\xc8nuk\xa85\\>oqd\xfd\xfb\xcf\
c\x96\xc5v\xc5\x27&\xf4,4\xa5\xba,nN7f\xf8h\xfa\xb5-\x99[\xb3rV$\x9aB\xcc\
\xde\xf9\xb2\x02A\xe1h\xf1\x93\xb5\xb7K\xae\x94u\x94\x1f\xdf\xb0\xf3\xae\
\xad\x15U\xc5;\xcc5\xc6\xda\xe5u\xc6zfo\xe9\xfeo\x0e\xb5}7\xd8\x14\xdc\\\
z\xdc\xda\xba\xe8\xe4\xb5\xb3\xab\xda\xe5\xe7\xcf\\,\xea
\xeb\x16\xff\xde\xad\xb7\xaf\xe7\xf6\xdd\xfb\xce\x03\x11O7\x0f=~\xbe\xd2\
f{\xa5w\x17L\x86
\xf3a\xc2\x97h\xc305\x87ZC\x9d\xa3=i\x0b\xdd\xc3\x89\xe6\xb4p\xd5\xdc\xd3\
\xbc\x14\xde#\xfe\x0e\xc1\x07BJ\xd8.\xda\xe9\xc48\xa7\xb9\xc4\x88#&D\xbb\
&K\x8c\xd2J\xb76\x99\xf3D\x9d\xfc\xfc\xa4\x08\xcf\x8e\xc9\x1a/j\xea\x11\
\x85yF\x98\xb7\x87\x0f5s\xc4\x0fJY@\x90J\x13X\x15|)D\xae\xd6\x856\x85s\xe7\
-\x89<\x1a\xed\x15S\x1571\xbe>1t\xe1\xf5\xd4\xcdi\xd1Ky\x19\x17?\xfeZ\x97\
oH\xc8\x0eX)1\x0d\x9a{\xf3.\xd8S\xb4\xfe\x93\xf4u\xca\x92\xa1\xb2c\xe5\
\xa6\x0dS6\xfd\xb2%{\xbb\xa0\xbaa\xe7\xbc\x9a?k\xd7\xd6y\xef\xb9\xd4P\xde\
\x18wp\xca\xb78<|Dtl\xf6\x8f\xebZ\xfbO\xadk\xf3m\xbf~\xa1\xf1\xd7\xf2\xcb\
\xa5W\xea\xaeZo\xa4\xdc\x1a\xbc\xd79\xf0\xe0\xaf\xf8\xe1\xe7\xaf\xf4NCD\
|\xf8&B\x90\x84\\l\xc7O\xb8O)\xa8\x0cj7\xf5\x80\x0e\xa7k\xe8\x17\x9c\x95\
\x1c+7\x93\xfb\x84W\xc1\xf7\xe3\xf7\x08\xb6\x09\xd3D\xbeN<\xa7\x01\xe7\x9b\
.}\xe2~WH\xbc\xa4\xc9n\x8d2\xcf\x89\x8d\x1e\x0b<\x05otNi\x98Z\xacH\x9c\xe1\
\xe7\xed\xe6#\xf0\x15\xf9y(U\x01)\xaa\xf5\x81\xcd\xc1OB\x82\xd4E\xa1g\xc2\
\xc5\xe4\xbd\xef\x8bFL&y\xefq\x09\xe7\x17\xa6\xa6\xdcY\xfcY\xfa[\x1fujJ\
\xb5a\xfa\xd1\xe5g\x8c\x959\x9a\xbc Fl\xb9\xb7\xbac\xcd\x81O7\xae\xcf-M\
\xf8\xdc\xef\x0b\xee\xc6\xab\x95M\xdb*\xaa\x97\xedT\xe5Q;Rg\xad\xffmo\xe7\
\xfe\x9eC\x0f\x0f\xbb5\xc56W\x1f\x1fjeN\x89\xce\x1em_q\xc1\xff\xa2\xad\xcb\
\xda\xfdG\xef\x83\xeb2k\xfa\x9d\x13\xfd\xd1\x8f\x9f\x0ev\x8c\\\xb0\xd9\x1c\
^\xb5\xf5\x94cOa\xf9n\xc9\x18?\xcb\xfe\x97\xc9\x9e\xe3\xf03\xab\xe1\xf0\
\x81\x86r`\x91\x15\x98\x0e\xa8\x89\x03|\xc2\x00w\xe2\xe5$1\x90\xaa\x06\
uS\x0f\xaao:\xa8\xfbR\xe2\xa6B\xb0\x9b\xdek\xe5*{\xbf\xaf\x91\x93H\xbf\xaf\
\x95{\x00\xc7\x99F\xfa\x06$\xc6\x05Z\xbd"J\x9bc\xd41Z\x8b\x81\xd8\xc01$\
0b\x01\xb4\xd0C\x81(\x12s\xc8\\\x07\x86\x90\x05\x06\xd8e\xe3\xdd\xfaO\x89\
\xff\x17-\x86Br\xa6\x02Qy\xe6"\xc6\x98\x95mQD\x90\xbf\x03\x83"*\xcfd^e1\
0JEl\xae>@\xa9\x08T\xa9\x82X\x9d\xe3\xdce\x89/\x01j\xc9?\x01p\xe2\xa9\x86\
\x0d\xff\x19\x03`\xee\xd2\xcd}j;\xa1\x00\x00\x00\x09pHYs\x00\x00\x0b\x13\
\x00\x00\x0b\x13\x01\x00\x9a\x9c\x18\x00\x00\x06EIDATH\x0d\xb5U[l\x14e\x14\
>\xb3;\xb3;\xd3\xbd\xf7\xb6\xd7\xde\xd8\xd2\xb2\xb4 R/\xd5
"\x96\xf8@\x88\x09Z\x13\xc5 \xe8\x13*h\x8a\x08\xfa\xa0\xc4\x07\xa2\x04\
\x8dV\x13//\x88\x891"\xf2 b\xc0 m\x11Q\xe4R\x81\xd2\x8b`[\xbb\xedv\xaf\xdd\
\x9d\xdd\xd9\xee\xec\\v=\xffH\xab &\xbe\xf8\x27\xdf\\\xfe9\xe7|\xe7\xfa\
\x0f\xc0\xff\xbc\xa8\xffj\xff\xfe\xfd\xb6h(\xb1\x8c\xd2\x15\x0c\xf62{\xf7\
\xbau\xeb\x92\xffE\x97\xfe7\xa1\xae\xae\xcdF\x86Yx\x1b\xcb\xb2\x977n\xdc\
\x98\x9a\x8eM\xaf\xbas\xf9\xf2/8\x96\x85\xef{\xbf{\x1c\xf5>\xdd\xbbw\xaf\
]\x14\xc5&Y\x1e8\xbbe\xcb\xbb\xf9\x9b\xd9\xd2\xddl\xb3\xab\xab\xcbXV\xd6\
\xf6\xc1\xa2\xc5-\xdfp\x9c\xf9\xbdM\x9b69\x84\x1c_\xc3\x95\xd8\xc1\xc0\xd9\
af&\xe3\xdb\xb0a\x03K\xbe\x11\x19"Ktnf\xeb\xa6\x110\xf9\xbc\xcd\xc0\x96\
\xdc\xe3\xad]h\xcdK\xca\xba\xfb\xdb\xdb\x9dF#\xd7\xac\xd3AQUe\xca\xef\x9f\
\xff\xb4\xc7\xe3\x0b\x94Wz\x1f\xf3\xd66Q\xa1\xf0\xd42\xa2\x83\x04\xd1\x1b\
I\xf4\xdf\xe8\xe8\xe80<\xfe\xe0\x83\xf6\xceW^\x89/\xbb\xfb.\x07\xa57\xdc\
W7/\x00\x1e_\xcd\xbcJg\x8dY\x92)\xaaX\xa4\xc0WUk\xf3\xfaj\x97\xd8\x1cN\xea\
\xd7\xe1~\x18\x1f\xb9\xfc\xea\xb3\x9d[\xbbw\xedz\xa9\xac\xb4\xd4\xad\x0e\
\x0c\x0c\xa8\xb3v\xe7\x8a\xbcs\xe7N\xd6WU\xf5\xbe\xd5bo\x0d\x06\xc7>q\xbb\
\xab\x9ei\xbe\xa5\xd5\x9b\x15U\x18\x1d\xb9
\xe1\xf0$d\x05\x01(\x8a\x02\x87\xa3\x14\xbc\xbe\x1aD5\x80\x9a\x85\xcb\x97\
~\xfe,9=\xd5\xe3\xf1\xf8\xb7f\x84\xd4\xa9\x89`p\x13\xda\x13\x09\xc9\\\x8a\
\x8cFc\xab\xdd\xe1yl\xf1-\xb7\x1b\xac\xf6\x8a]nO5\x083\x12\x9c?w\x06\x8c\
,\x07\x81\xc0\x12\xb0\xda\x1cP,\x16 \x1e\x8b\x00:\x01\x91H\x04nki\x81\xe6\
Ew<\x9a\x88\x87\x1f\xad\xf37\xc1\xc5\x0bgjc\xd1\xe8>\xb4\xdds\x1dA\xb1X\
\xbc<\x19\x1c;(\x8a\xca\xc3\xb5\xf5Mt:\xa3\xc2\x95\xdf\x86\xc1\xe5\xae\x86\
J\xa7\x87\xc8\x82\xa2(\xda\xbd\xac\xdc\x05\x8e\xd2
\x98\x9c\x18\x87\x8b\x97\xfa\xa1\xa11\x00&[\x15\x9c>}J\x99\x8eM\x1e$\xb6\
4A\xbc\xcc\xa5\xe8\xda\x06\xb5{w\xd7\xe7\x8b\x96.\xef\x98\x99\xc9cJ\xd2\
H\xe0\xd3\xbc\x0e\x8e\x0d\xa8\xa1\xd0\xc8\x90\x9e\xd2Q.\x9fAU\xf5\x02]\
\xb1\x080\x15
\x82\xc5b\x83\x12\x13\x0b\x97\xfaz\xbf|q\xdbs\x8f\xa0\xad\xc2,\x81\x96\
\xa2\x1d;v8TUZ#I\xb2\x93f\xe8;\x19\xda\x003\xb9$\x18\x8c\x1c\xc8\xb2\x82\
\x9e\x0e\xe6\xae\x0c\x9e\xfehll\xfcU\x8e\xe3\xe8D"\xb2SU\x94\xa7\xbcU\x01\
\x8e\xe5L d\x05\xac\x0b\xb6\xb0\xc1\xd0\xb6y\xf33\xdb\xb0\xe3F\xcb\xcb\xcb\
\x8f\xa2]^#\x10\x84\xd4\xca\xfbW\xad\xddWW7\x0f\xd2\x99\x1cB\x06E*\x00C\
\xd3\x90\x13\xf3\x10\x1c\x1d\xbaz\xfcx\xcf\xb6s\xe7\xce\xc9\xc43\xec\xb6\
\xe7Yl\xe3\xd2\xf2\xda%\x14EC\x01{F\xc8\xe6`i\xcb=\xae{W\xb4\xbf><4\x04\
?\x9e8\xb2\x06E\xbf\xd6\x06\x8d*\x14\x8b\x91h\x12\x06\x06\x830\xfa{\x04\
\xf8\xb4\x80\xc9\xa3@EMY\x96\xa1P(P{\xf6\x1c\x98k\xe9\xed\xdb\xb7\xeb
EE\x96%\x09\x14\x15\xb3A\xe9 \x9d\xce\xc2\xe8x\x14\x06\x87& \xc5\xcf\x80\
\\T\x0c\xc4\x19-\x02\x93\xd5\xd1}\xb1\xef\xf8\x13\xa8\xe1\xadt\xce\xdf:\
\xaf\xa1\xb5L\xaf\xd7\xa1g*0x\xafoX4\xff\xec\xd9\x03o\x1f:t\xa8\x93(\xf5\
v\xf7\xeeih\\\xb2\x18\xd3\x09\xa2(\x81N\xa7\x07IR`\xe4\xca\x99L<<\xfc\x86\
\x8e6\x04\xadh\x93\xc8\xdeXdCg\xe7\xcb_\xf9\x1b\xef~\x80+1\x01k\xc4\x14\
\xe5$pVXA\x9c\x09\x17\xf2\xf9L?Q2\xb2\xd6f\xb6\xc4\xa5\x8b\xc4x\xe0X\x03\
\xe4\xf3*\xcae\xe1\xea\xd0\x0f\xdf\xbf\xf5\xd6\xae\x07P$G\xe4\xc8\x9a\x0b\
{\xfd\xfa\xf5e+W\xae\xfa\x10\xdbr\x8d\xd9\xea\xd4\xe5\xb0\x8b,f#\xc9\x14\
D\xe3i`K\xec\x14N\xaf\xd3fw93\x02EME\x92`*1\x00\x83Q$S\x02\x16\x98\xc1H\
\x14_Ss\xc0\xdf\xd8P\xdf{\xe1\xc2\x05\x8dDK\x11a\x92$\xa9\x9e1\xda\xd6\xb2\
%U\xf4\xaf\xc3\xe7\xc1lq\x82\xaa*PS]\x01&l\xc1\xc9P\x02\xae\\\x9d$\xa2\xe0\
\xb0\x9b\xc1\xe7-\xc3\x1a\x15`<\x18\x87T2\x8e-\x1d\x05\x9f/\xa07\x1a\x13\
k%i\xa2\x0b\xc5\x12Dv\x8e@U\xd5\xbe\xd0\xc4\xc8g\x89x\xa45\x93\x8e\xee\xb3\
\xda\\\xcfJ\xeef\x9f(\xca\xe0q\x97Bc\xbd\x17\x18\xc3\x9f\x01c;Ch*\x09\xe1\
H
\xd2|\x02"S\x17\x27\xb2B\xfc\x9d\xe9x\xf0\xc9\xbc\x98\xfd\x89\xd8"\xc6\
\xc9\xba\xae\x06+V\xac\xa0q\x99\x8e\x1d;\xc6wt<\xb4\xcd\xed[\xbc\xdbb\xab\
\xc3AS0\x15\x1c\xd04\x85\x1dU\xd4 K9l\x1e\x06\x04~\x0c&\x83\xbf\xbcp\xe0\
\xc0\xc17\xdb\xdb\xdbm8\xed\xd9\x9e\x9e\x9e?G\xfeF\x02\x8d\x12/\xabW\xaf\
\xc6\xf3\xcc{\xb2\xd6\xdf\xb60\x1c\x1a(f\x85\xd8\x09\x9aao\xad\xa8\x0cX\
IKF\xc3\xfd)U\x11\xcf\x9b\xcc\xce\xfb\\\x9e\x005\xf6\xdb\xc9\xc1\xe4t\xa8\
\xed\xf0\xe1\xc3\xff\xf8\xcb\xcd\x15\xf9\x1a\x19\x99\x0b&\x16\x8b1\x95\x95\
\x95\xb7\x8b\xa2\xe0\x8f\xc5\xc6\xbe\xfb\xf1\xd4\xd1-:\x10\x15\xa7{A\x1b\
)\xfa`\xff\xb7\xef\xf7\xf5\x9d~\xcdl1\xcf\x97\xf2Yw\x9a\x8ft\x9f\xfa\xe1\
\xe4\xd7\xb9\\\x8e\x1c\xd3x\x80\xfc\xb5fk@RE\xc88\x845\x95J\xd9\x8e\x1c\
9\xf4\xb1\xcb\xe5\x1aN&\x93\xa9l6\xbb\xd4b)\xb5\xa7\xf90\xa6\x89\x81x\x9c\
\xb7\x85B\xf1\x16\x9e?z\x04\x8f\x84c\xa1P\xe8\x04\x0ed9\xea\xf2\x08\x9c\
R \x13\xaf\x9dG\xb35\xb8\x8e\x00?\xda\x11\x16\x04\xf9\x0d\x12\xe8\xcc\xb8\
\xbc^w#M\xeb\xf5\x13\x13S\x83<\xcf\xa7q\x9fx\x9cE\x90\x96\xcc R\x08B !\xb4\
Hf\x09\xf0]+\xb8\x96"|f\x10$\xbaY\xcc\xfe\xbb\xb5\xb3\xe8\xda>\xde4\x02\
RP\x02\xf2\x8d\x80<\xcf\xa5\xe9\x0f\x8f\x85\xb5+>d\xe0\x9a\x00\x00\x00\x00\
IEND\xaeB`\x82'''

    list_remove_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x00\x06bKGD\x00\x00\x00\x00\x00\x00\xf9C\xbb\x00\
\x00\x00\x09pHYs\x00\x00\x0d\xd7\x00\x00\x0d\xd7\x01B(\x9bx\x00\x00\x00\
\x07tIME\x07\xd6\x01\x0b\x0f;"\x00\\\x12\xc2\x00\x00\x00\x84IDAT8\xcb\xed\
\x91\xb1\x09\x83P\x10\x86\xbf\x07i\xdc\xc0:+\xe8\x08\x19#\xadmF\x08\x19\
 \x0b\x88\xads\xc4\x05t\x88\xd4\xb6"D\xf3\xeeO!\xca\xb3\xb33\x85\x1f\x1c\
\x1c\x07\xffw\x1c\x07\x07\xfb\xe3\xe6&\xcd\xca\x1aH6\xe6\x9a\xba\xb8\xa6\
\x00\xa7`\x98<o\x17F\x13\x0e\x18\xbdV\x09i*\x07\xdc\xf3\xd7\xb2(\x14\xd0\
}<\xef\xb6G\x023a\x82~\x10\xde\x8b\xaf\x0938\xc7\xd1J\x1c
\x9aG^m>\xe1\xf8\xfe?\xf1\x03\xacS-\xdbF\xe4\x80\xd8\x00\x00\x00\x00IE\
ND\xaeB`\x82'''

    list_add_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x00\x06bKGD\x00\x00\x00\x00\x00\x00\xf9C\xbb\x00\
\x00\x00\x09pHYs\x00\x00\x0d\xd7\x00\x00\x0d\xd7\x01B(\x9bx\x00\x00\x00\
\x07tIME\x07\xd6\x01\x0b\x10\x00\x11\x94Dx\xa1\x00\x00\x00\xd0IDAT8\xcb\
\xcd\x91\xbd\x0e\xc1`\x14\x86\x1f\xd2\xc5`\xb7r\x07\xd2\xba\x81\xc6`6[;\
tq\x07D\xd2\xc4d\x17\xb1Z\x0d&\x83\x84\x1b\xe8g7Z,Vi\xe2\xa7\xdf1\x10\x8a\
\xfa\x8b\x04\xefv\xf2\x9d\xbc\xf9\x9e\xe7\xc0\xaf\x93\xb8\xf7`9=\x1f0\x8f\
\xa3\xf2\xbb\x15+n/\xf9\xa0\xdc\xf4\\\x1b\xcf\xb5\x89\x14\xbdU\xf0R>.0\xee\
0\xc79\x91\xc8xrbD\x99[\xd5"[-$\x80mx\xde\xf7\\\x1b\x11\x109X\xafw\xc6\xe6\
\xcd\x0f\x00V\xeb\x90\xf92@\x04\xb4\x16\xb4@\xb0\x11\xc2P\xd8iAk\xc8eR\xf1\
\x08\x80jt&\x17\x08\xe5R\x01\x80\xc1\xc8\xbf&RO\xe5XNO\x86\xd3\x854\xfb\
3\xb9\xe2\xff\xf2\x19\xf3\xd9\xf4kg\x8c\x89\xaa\xb5O\xb6\x15\x9b=TrK\x0b\
\x8b\xb2w\x8e\x00\x00\x00\x00IEND\xaeB`\x82'''

    W__png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x02\x00\x00\x00\
\x90\x91h6\x00\x00\x00!tEXtSoftware\x00GraphicConverter (Intel)w\x87\xfa\
\x19\x00\x00\x01\xd6IDATx\x9cb\xf8\xb7r\xd5\xbf]\xbbAh\xde\x82\xbf?~\xfc\
\xeb\xe8\xfa\xf3\xf1\xd3\xbf\xf9\x0b\xffm\xdb\xfeo\xfb\x8e\xbfk\xd7\xff\
\xfb\xf7\xef?\x12`x\xef\xe6\xf9KH\xec\xb3\xb8\xf4#u\xadk\xf3\xe6\xff\xe5\
\x17~8c\xd6\x1bK\x9b/\x12\xd2\xdfE$.Y\xdb\xbdz\xf5
E\x03\x90\xff>)\xe5\x94\x97\xef\xc5\x8b\x17?\xcc\x9d\xffIB\xe6Zq\xc9\xf3\
\xe7\xcf_\x95W\x9evt\xb9p\xe1\xc2\xcf\x9f?Q4\x00\xf1\xbfy\xf3o\xb9\xba\xff\
\xfe\xfd\xfb_o\xffUs\xab\xeb\xe1\x91\xff\xfe\xfdW\xd7p45\x1d\xc8\xf8\x8f
\xc0\x1a\x0e\x1ezh`\xfc\xf9\xf3\xe7\xf9E\x27RRo;8\x01M\xfd\x97\x90|\xb4\
\xbd\xe3?\x06\x00i\xf8\xff\xf4\xe9[y\xa5\x17/^\xfc\x0b
=6g\xeec\x1d\xfd\x8f\x1f?\xfeur=\xbaj\x15\x0e\x0d\xff\xfe\xfd\x92\x91\xbf\
u\xe3\xc6\x0fK\x9b3\xa7O\xbfWQ\xfa\xf4\xe9\x0f\x0d\xedS\x27O\xe2\xd0\xf0\
\xff\xff_\x1b\xfb\xeb{\xf7>\xd7\xd2\xbds\xe7\xceo\x13\xf3\x9b\xa7O?SV\x03\
\xb2qj\xf8\x97\x98|\xbd\xb3\xfb\x86\x91\xc9\x9b7o\xfe\xfa\x07]\x9b8\xe9\
\xaa\xa9\xc5\xbbw\xefpkhi\xbb\x19\x14r\xce\xd5\xfd\xfb\xf7\xef\xffr\xf2\
nDD\x9d\xf2\xf5G\x0bPT\x0d+V\xbeP\xd7:\x11\x17\x0f
\xd0\x8e\xae\xa7\xdaz\xc7\xb2s\xd0\xe2\x18U\xc3\x99\xb3\x04D\x8eU\xd7\
\x80\xd8\xcb\x96\xff\x16\x14=\xda\xd7\xff\xff\xf1\xe3;v!\xa3\xbfO\x9eB\
5\xfc\xff\xfc\xf9\x8f\x98\xd4\xc1y\xf3A\x1a.]\x06&\x96\xc3[\xb6\xfc[\xbc\
\x04\x98:\x90\xd1\x8d\xb6\x0e\x06\xb8]7\x8f\x1c\x81\x07\xcb\xd9\xed\xdb\
\x9f={\xf6\xeb\xd7\xaf#G\x8e\x1cB\x02\x97/_f\xf8O" Y\x03\x00\x00\x00\xff\
\xff\x03\x00\xc6\xe0r\xe5V\xd2\xec5\x00\x00\x00\x00IEND\xaeB`\x82'''

    wx.MemoryFSHandler.AddFile('XRC/OGRegression/OGRegression_xrc', OGRegression_xrc)
    wx.MemoryFSHandler.AddFile('XRC/OGRegression/gear_png', gear_png)
    wx.MemoryFSHandler.AddFile('XRC/OGRegression/list_remove_png', list_remove_png)
    wx.MemoryFSHandler.AddFile('XRC/OGRegression/list_add_png', list_add_png)
    wx.MemoryFSHandler.AddFile('XRC/OGRegression/W__png', W__png)
    __res.Load('memory:XRC/OGRegression/OGRegression_xrc')

