# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIALOGWEIGHTS(wx.Dialog):
#!XRCED:begin-block:xrcDIALOGWEIGHTS.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIALOGWEIGHTS.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOGWEIGHTS")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.InputPanel = xrc.XRCCTRL(self, "InputPanel")
        self.InputShapeChoice = xrc.XRCCTRL(self, "InputShapeChoice")
        self.OpenShape = xrc.XRCCTRL(self, "OpenShape")
        self.OutputPanel = xrc.XRCCTRL(self, "OutputPanel")
        self.OutputText = xrc.XRCCTRL(self, "OutputText")
        self.OpenOutput = xrc.XRCCTRL(self, "OpenOutput")
        self.IdvarChoice = xrc.XRCCTRL(self, "IdvarChoice")
        self.addIDVar = xrc.XRCCTRL(self, "addIDVar")
        self.weightsNotebook = xrc.XRCCTRL(self, "weightsNotebook")
        self.ContiguityPanel = xrc.XRCCTRL(self, "ContiguityPanel")
        self.RadioQueen = xrc.XRCCTRL(self, "RadioQueen")
        self.ContiguityOrderSpin = xrc.XRCCTRL(self, "ContiguityOrderSpin")
        self.RadioRook = xrc.XRCCTRL(self, "RadioRook")
        self.ContiguityIncludeLowerCheck = xrc.XRCCTRL(self, "ContiguityIncludeLowerCheck")
        self.DistancePanel = xrc.XRCCTRL(self, "DistancePanel")
        self.DdistMethodChoice = xrc.XRCCTRL(self, "DdistMethodChoice")
        self.ThresholdRadio = xrc.XRCCTRL(self, "ThresholdRadio")
        self.ThresholdSlider = xrc.XRCCTRL(self, "ThresholdSlider")
        self.CutoffText = xrc.XRCCTRL(self, "CutoffText")
        self.KnnRadio = xrc.XRCCTRL(self, "KnnRadio")
        self.NumNeighSpin = xrc.XRCCTRL(self, "NumNeighSpin")
        self.InverseRadio = xrc.XRCCTRL(self, "InverseRadio")
        self.PowerSpin = xrc.XRCCTRL(self, "PowerSpin")
        self.KernelPanel = xrc.XRCCTRL(self, "KernelPanel")
        self.KdistMethodChoice = xrc.XRCCTRL(self, "KdistMethodChoice")
        self.KFuncChoice = xrc.XRCCTRL(self, "KFuncChoice")
        self.KNumNeighSpin = xrc.XRCCTRL(self, "KNumNeighSpin")
        self.CreateButton = xrc.XRCCTRL(self, "CreateButton")
        self.CloseButton = xrc.XRCCTRL(self, "CloseButton")

        self.Bind(wx.EVT_CHOICE, self.OnChoice_InputShapeChoice, self.InputShapeChoice)
        self.Bind(wx.EVT_BUTTON, self.OnButton_OpenShape, self.OpenShape)
        self.Bind(wx.EVT_TEXT, self.OnText_OutputText, self.OutputText)
        self.Bind(wx.EVT_BUTTON, self.OnButton_OpenOutput, self.OpenOutput)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_IdvarChoice, self.IdvarChoice)
        self.Bind(wx.EVT_BUTTON, self.OnButton_addIDVar, self.addIDVar)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_RadioQueen, self.RadioQueen)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_ContiguityOrderSpin, self.ContiguityOrderSpin)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_RadioRook, self.RadioRook)
        self.Bind(wx.EVT_CHECKBOX, self.OnCheckbox_ContiguityIncludeLowerCheck, self.ContiguityIncludeLowerCheck)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_DdistMethodChoice, self.DdistMethodChoice)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_ThresholdRadio, self.ThresholdRadio)
        self.Bind(wx.EVT_SCROLL, self.OnScroll_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_TOP, self.OnScroll_top_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_BOTTOM, self.OnScroll_bottom_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEUP, self.OnScroll_lineup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEDOWN, self.OnScroll_linedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEUP, self.OnScroll_pageup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEDOWN, self.OnScroll_pagedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBTRACK, self.OnScroll_thumbtrack_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBRELEASE, self.OnScroll_thumbrelease_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_CHANGED, self.OnScroll_changed_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL, self.OnScroll_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_TOP, self.OnScroll_top_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_BOTTOM, self.OnScroll_bottom_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEUP, self.OnScroll_lineup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEDOWN, self.OnScroll_linedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEUP, self.OnScroll_pageup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEDOWN, self.OnScroll_pagedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBTRACK, self.OnScroll_thumbtrack_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBRELEASE, self.OnScroll_thumbrelease_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_CHANGED, self.OnScroll_changed_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_TEXT, self.OnText_CutoffText, self.CutoffText)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_KnnRadio, self.KnnRadio)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_NumNeighSpin, self.NumNeighSpin)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_InverseRadio, self.InverseRadio)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_PowerSpin, self.PowerSpin)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_KdistMethodChoice, self.KdistMethodChoice)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_KFuncChoice, self.KFuncChoice)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_KNumNeighSpin, self.KNumNeighSpin)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnNotebook_page_changed_weightsNotebook, self.weightsNotebook)
        self.Bind(wx.EVT_BUTTON, self.OnButton_CreateButton, self.CreateButton)
        self.Bind(wx.EVT_BUTTON, self.OnButton_CloseButton, self.CloseButton)
        self.Bind(wx.EVT_CLOSE, self.OnClose)

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_InputShapeChoice
    def OnChoice_InputShapeChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_InputShapeChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_InputShapeChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_OpenShape
    def OnButton_OpenShape(self, evt):
        # Replace with event handler code
        print "OnButton_OpenShape()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_OpenShape        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnText_OutputText
    def OnText_OutputText(self, evt):
        # Replace with event handler code
        print "OnText_OutputText()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnText_OutputText        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_OpenOutput
    def OnButton_OpenOutput(self, evt):
        # Replace with event handler code
        print "OnButton_OpenOutput()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_OpenOutput        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_IdvarChoice
    def OnChoice_IdvarChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_IdvarChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_IdvarChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_addIDVar
    def OnButton_addIDVar(self, evt):
        # Replace with event handler code
        print "OnButton_addIDVar()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_addIDVar        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioQueen
    def OnRadiobutton_RadioQueen(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_RadioQueen()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioQueen        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_ContiguityOrderSpin
    def OnSpinctrl_ContiguityOrderSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_ContiguityOrderSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_ContiguityOrderSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioRook
    def OnRadiobutton_RadioRook(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_RadioRook()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioRook        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnCheckbox_ContiguityIncludeLowerCheck
    def OnCheckbox_ContiguityIncludeLowerCheck(self, evt):
        # Replace with event handler code
        print "OnCheckbox_ContiguityIncludeLowerCheck()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnCheckbox_ContiguityIncludeLowerCheck        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_DdistMethodChoice
    def OnChoice_DdistMethodChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_DdistMethodChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_DdistMethodChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_ThresholdRadio
    def OnRadiobutton_ThresholdRadio(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_ThresholdRadio()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_ThresholdRadio        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider
    def OnScroll_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider
    def OnScroll_top_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_top_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider
    def OnScroll_bottom_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_bottom_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider
    def OnScroll_lineup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_lineup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider
    def OnScroll_linedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_linedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider
    def OnScroll_pageup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pageup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider
    def OnScroll_pagedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pagedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider
    def OnScroll_thumbtrack_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbtrack_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider
    def OnScroll_thumbrelease_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbrelease_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider
    def OnScroll_changed_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_changed_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider
    def OnScroll_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider
    def OnScroll_top_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_top_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider
    def OnScroll_bottom_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_bottom_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider
    def OnScroll_lineup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_lineup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider
    def OnScroll_linedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_linedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider
    def OnScroll_pageup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pageup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider
    def OnScroll_pagedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pagedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider
    def OnScroll_thumbtrack_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbtrack_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider
    def OnScroll_thumbrelease_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbrelease_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider
    def OnScroll_changed_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_changed_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnText_CutoffText
    def OnText_CutoffText(self, evt):
        # Replace with event handler code
        print "OnText_CutoffText()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnText_CutoffText        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_KnnRadio
    def OnRadiobutton_KnnRadio(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_KnnRadio()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_KnnRadio        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_NumNeighSpin
    def OnSpinctrl_NumNeighSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_NumNeighSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_NumNeighSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_InverseRadio
    def OnRadiobutton_InverseRadio(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_InverseRadio()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_InverseRadio        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_PowerSpin
    def OnSpinctrl_PowerSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_PowerSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_PowerSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_KdistMethodChoice
    def OnChoice_KdistMethodChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_KdistMethodChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_KdistMethodChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_KFuncChoice
    def OnChoice_KFuncChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_KFuncChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_KFuncChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_KNumNeighSpin
    def OnSpinctrl_KNumNeighSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_KNumNeighSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_KNumNeighSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnNotebook_page_changed_weightsNotebook
    def OnNotebook_page_changed_weightsNotebook(self, evt):
        # Replace with event handler code
        print "OnNotebook_page_changed_weightsNotebook()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnNotebook_page_changed_weightsNotebook        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_CreateButton
    def OnButton_CreateButton(self, evt):
        # Replace with event handler code
        print "OnButton_CreateButton()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_CreateButton        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_CloseButton
    def OnButton_CloseButton(self, evt):
        # Replace with event handler code
        print "OnButton_CloseButton()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_CloseButton        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnClose        


class xrcmainGUI(wx.Frame):
#!XRCED:begin-block:xrcmainGUI.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainGUI.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "mainGUI")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.ModelWeigths = xrc.XRCCTRL(self, "ModelWeigths")
        self.KernelWeights = xrc.XRCCTRL(self, "KernelWeights")
        self.WeightsProps = xrc.XRCCTRL(self, "WeightsProps")
        self.Quit = xrc.XRCCTRL(self, "Quit")

        self.Bind(wx.EVT_BUTTON, self.OnButton_ModelWeigths, self.ModelWeigths)
        self.Bind(wx.EVT_BUTTON, self.OnButton_KernelWeights, self.KernelWeights)
        self.Bind(wx.EVT_BUTTON, self.OnButton_WeightsProps, self.WeightsProps)
        self.Bind(wx.EVT_BUTTON, self.OnButton_Quit, self.Quit)

#!XRCED:begin-block:xrcmainGUI.OnButton_ModelWeigths
    def OnButton_ModelWeigths(self, evt):
        # Replace with event handler code
        print "OnButton_ModelWeigths()"
#!XRCED:end-block:xrcmainGUI.OnButton_ModelWeigths        

#!XRCED:begin-block:xrcmainGUI.OnButton_KernelWeights
    def OnButton_KernelWeights(self, evt):
        # Replace with event handler code
        print "OnButton_KernelWeights()"
#!XRCED:end-block:xrcmainGUI.OnButton_KernelWeights        

#!XRCED:begin-block:xrcmainGUI.OnButton_WeightsProps
    def OnButton_WeightsProps(self, evt):
        # Replace with event handler code
        print "OnButton_WeightsProps()"
#!XRCED:end-block:xrcmainGUI.OnButton_WeightsProps        

#!XRCED:begin-block:xrcmainGUI.OnButton_Quit
    def OnButton_Quit(self, evt):
        # Replace with event handler code
        print "OnButton_Quit()"
#!XRCED:end-block:xrcmainGUI.OnButton_Quit        


class xrcAddIDVar(wx.Dialog):
#!XRCED:begin-block:xrcAddIDVar.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcAddIDVar.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "AddIDVar")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.idVarName = xrc.XRCCTRL(self, "idVarName")
        self.existingVarsListBox = xrc.XRCCTRL(self, "existingVarsListBox")
        self.save = xrc.XRCCTRL(self, "save")
        self.cancel = xrc.XRCCTRL(self, "cancel")

        self.Bind(wx.EVT_BUTTON, self.OnButton_save, self.save)
        self.Bind(wx.EVT_BUTTON, self.OnButton_cancel, self.cancel)

#!XRCED:begin-block:xrcAddIDVar.OnButton_save
    def OnButton_save(self, evt):
        # Replace with event handler code
        print "OnButton_save()"
#!XRCED:end-block:xrcAddIDVar.OnButton_save        

#!XRCED:begin-block:xrcAddIDVar.OnButton_cancel
    def OnButton_cancel(self, evt):
        # Replace with event handler code
        print "OnButton_cancel()"
#!XRCED:end-block:xrcAddIDVar.OnButton_cancel        


class xrcweightsProperties(wx.Dialog):
#!XRCED:begin-block:xrcweightsProperties.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcweightsProperties.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "weightsProperties")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.selectWChoice = xrc.XRCCTRL(self, "selectWChoice")
        self.nameTC = xrc.XRCCTRL(self, "nameTC")
        self.transformChoice = xrc.XRCCTRL(self, "transformChoice")
        self.islandsTC = xrc.XRCCTRL(self, "islandsTC")
        self.idListChoice = xrc.XRCCTRL(self, "idListChoice")
        self.weightsTC = xrc.XRCCTRL(self, "weightsTC")
        self.cardinalitiesTC = xrc.XRCCTRL(self, "cardinalitiesTC")
        self.idsTC = xrc.XRCCTRL(self, "idsTC")
        self.histogramTC = xrc.XRCCTRL(self, "histogramTC")
        self.viewerButton = xrc.XRCCTRL(self, "viewerButton")
        self.closeButton = xrc.XRCCTRL(self, "closeButton")

        self.Bind(wx.EVT_CHOICE, self.OnChoice_selectWChoice, self.selectWChoice)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_transformChoice, self.transformChoice)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_idListChoice, self.idListChoice)
        self.Bind(wx.EVT_BUTTON, self.OnButton_viewerButton, self.viewerButton)
        self.Bind(wx.EVT_BUTTON, self.OnButton_closeButton, self.closeButton)

#!XRCED:begin-block:xrcweightsProperties.OnChoice_selectWChoice
    def OnChoice_selectWChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_selectWChoice()"
#!XRCED:end-block:xrcweightsProperties.OnChoice_selectWChoice        

#!XRCED:begin-block:xrcweightsProperties.OnChoice_transformChoice
    def OnChoice_transformChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_transformChoice()"
#!XRCED:end-block:xrcweightsProperties.OnChoice_transformChoice        

#!XRCED:begin-block:xrcweightsProperties.OnChoice_idListChoice
    def OnChoice_idListChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_idListChoice()"
#!XRCED:end-block:xrcweightsProperties.OnChoice_idListChoice        

#!XRCED:begin-block:xrcweightsProperties.OnButton_viewerButton
    def OnButton_viewerButton(self, evt):
        # Replace with event handler code
        print "OnButton_viewerButton()"
#!XRCED:end-block:xrcweightsProperties.OnButton_viewerButton        

#!XRCED:begin-block:xrcweightsProperties.OnButton_closeButton
    def OnButton_closeButton(self, evt):
        # Replace with event handler code
        print "OnButton_closeButton()"
#!XRCED:end-block:xrcweightsProperties.OnButton_closeButton        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    weights_view_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIALOGWEIGHTS">
    <object class="wxBoxSizer">
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxPanel" name="InputPanel">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <label>Input File</label>
                        <XRCED>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                    <object class="sizeritem">
                      <object class="wxChoice" name="InputShapeChoice">
                        <XRCED>
                          <events>EVT_CHOICE</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                      <border>5</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxBitmapButton" name="OpenShape">
                        <bitmap stock_id="wxART_FILE_OPEN"/>
                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_RIGHT</flag>
                      <border>2</border>
                    </object>
                  </object>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_HORIZONTAL</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxPanel" name="OutputPanel">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <label>Save output as</label>
                        <XRCED>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                    <object class="sizeritem">
                      <object class="wxTextCtrl" name="OutputText">
                        <style>wxTE_READONLY</style>
                        <XRCED>
                          <events>EVT_TEXT</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                      <border>5</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxBitmapButton" name="OpenOutput">
                        <bitmap stock_id="wxART_FILE_SAVE"/>
                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                  </object>
                  <enabled>0</enabled>
                  <hidden>1</hidden>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_HORIZONTAL</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Select an ID Variable for the weights file</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                    <border>2</border>
                  </object>
                  <object class="spacer">
                    <size>3,5d</size>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>2</border>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="IdvarChoice">
                      <XRCED>
                        <events>EVT_CHOICE</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxALL|wxALIGN_CENTRE</flag>
                    <border>2</border>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBitmapButton" name="addIDVar">
                      <bitmap>___regression_rc_list_add_png</bitmap>
                      <tooltip>Add ID Variable...</tooltip>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE</flag>
                    <border>2</border>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxNotebook" name="weightsNotebook">
                      <object class="notebookpage">
                        <object class="wxPanel" name="ContiguityPanel">
                          <object class="wxBoxSizer">
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxFlexGridSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="RadioQueen">
                                        <label>Queen</label>
                                        <value>1</value>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>25,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <label>Order of contiguity</label>
                                            <XRCED>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSpinCtrl" name="ContiguityOrderSpin">
                                            <value>1</value>
                                            <min>1</min>
                                            <XRCED>
                                              <events>EVT_SPINCTRL</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="RadioRook">
                                        <label>Rook</label>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>25,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="sizeritem">
                                          <object class="wxCheckBox" name="ContiguityIncludeLowerCheck">
                                            <label>Include lower orders</label>
                                            <XRCED>
                                              <events>EVT_CHECKBOX</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                      </object>
                                    </object>
                                    <cols>3</cols>
                                    <rows>2</rows>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                                  <border>2</border>
                                </object>
                                <orient>wxHORIZONTAL</orient>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                              <border>2</border>
                            </object>
                            <orient>wxVERTICAL</orient>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <label>Contiguity</label>
                        <selected>1</selected>
                      </object>
                      <object class="notebookpage">
                        <object class="wxPanel" name="DistancePanel">
                          <object class="wxBoxSizer">
                            <orient>wxVERTICAL</orient>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxStaticText">
                                        <label>Select distance metric</label>
                                      </object>
                                      <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE</flag>
                                      <border>6</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxChoice" name="DdistMethodChoice">
                                        <XRCED>
                                          <events>EVT_CHOICE</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <option>1</option>
                                      <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE</flag>
                                      <border>10</border>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                  </object>
                                  <option>1</option>
                                  <flag>wxBOTTOM|wxEXPAND</flag>
                                  <border>10</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="ThresholdRadio">
                                        <label>Threshold Distance</label>
                                        <value>1</value>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="spacer">
                                          <size>25,5d</size>
                                          <flag>wxLEFT|wxALL</flag>
                                          <XRCED>
                                            <assign_var>1</assign_var>
                                          </XRCED>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSlider" name="ThresholdSlider">
                                            <size>150,-1d</size>
                                            <value>0</value>
                                            <min>0</min>
                                            <max>100000</max>
                                            <style>wxSL_HORIZONTAL</style>
                                            <XRCED>
                                              <events>EVT_SCROLL|EVT_SCROLL_TOP|EVT_SCROLL_BOTTOM|EVT_SCROLL_LINEUP|EVT_SCROLL_LINEDOWN|EVT_SCROLL_PAGEUP|EVT_SCROLL_PAGEDOWN|EVT_SCROLL_THUMBTRACK|EVT_SCROLL_THUMBRELEASE|EVT_SCROLL_CHANGED|EVT_SCROLL|EVT_SCROLL_TOP|EVT_SCROLL_BOTTOM|EVT_SCROLL_LINEUP|EVT_SCROLL_LINEDOWN|EVT_SCROLL_PAGEUP|EVT_SCROLL_PAGEDOWN|EVT_SCROLL_THUMBTRACK|EVT_SCROLL_THUMBRELEASE|EVT_SCROLL_CHANGED</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                                          <border>2</border>
                                        </object>
                                      </object>
                                      <flag>wxLEFT|wxALL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <object class="spacer">
                                          <size>25,5d</size>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <label>Cut-off point</label>
                                          </object>
                                          <flag>wxLEFT|wxALL|wxADJUST_MINSIZE</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxTextCtrl" name="CutoffText">
                                            <style>wxTE_RIGHT</style>
                                            <XRCED>
                                              <events>EVT_TEXT</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxLEFT|wxRIGHT</flag>
                                          <border>5</border>
                                        </object>
                                      </object>
                                    </object>
                                    <orient>wxVERTICAL</orient>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxLEFT|wxALL</flag>
                                  <border>2</border>
                                </object>
                                <object class="spacer">
                                  <size>3,3d</size>
                                  <XRCED>
                                    <assign_var>1</assign_var>
                                  </XRCED>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="KnnRadio">
                                        <size>80,-1d</size>
                                        <label>k-Nearest Neighbors</label>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>5,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <size>50,-1d</size>
                                            <label># of neighbors</label>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSpinCtrl" name="NumNeighSpin">
                                            <size>45,-1d</size>
                                            <value>4</value>
                                            <min>2</min>
                                            <XRCED>
                                              <events>EVT_SPINCTRL</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                        </object>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>2</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="InverseRadio">
                                        <size>80,-1d</size>
                                        <label>Inverse Distance</label>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>5,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <size>50,-1d</size>
                                            <label>Power</label>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSpinCtrl" name="PowerSpin">
                                            <size>45,-1d</size>
                                            <value>1</value>
                                            <min>1</min>
                                            <XRCED>
                                              <events>EVT_SPINCTRL</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                        </object>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>2</border>
                                </object>
                                <orient>wxVERTICAL</orient>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                              <border>2</border>
                            </object>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <label>Distance</label>
                      </object>
                      <object class="notebookpage">
                        <object class="wxPanel" name="KernelPanel">
                          <object class="wxBoxSizer">
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxStaticText">
                                        <label>Select distance metric</label>
                                      </object>
                                      <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxChoice" name="KdistMethodChoice">
                                        <XRCED>
                                          <events>EVT_CHOICE</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <option>1</option>
                                      <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE</flag>
                                      <border>10</border>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                  </object>
                                  <option>1</option>
                                  <flag>wxBOTTOM|wxEXPAND</flag>
                                  <border>10</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxStaticText">
                                        <size>50,-1d</size>
                                        <label>Kernel function</label>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxChoice" name="KFuncChoice">
                                        <content>
                                          <item>Uniform</item>
                                          <item>Triangular</item>
                                          <item>Epanechnikov</item>
                                          <item>Quartic</item>
                                          <item>Gaussian</item>
                                        </content>
                                        <selection>0</selection>
                                        <XRCED>
                                          <events>EVT_CHOICE</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>30,-1d</size>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                  </object>
                                  <flag>wxTOP|wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                  <border>2</border>
                                </object>
                                <object class="spacer">
                                  <size>2,2d</size>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxStaticText">
                                        <size>50,-1d</size>
                                        <label># of neighbors</label>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxSpinCtrl" name="KNumNeighSpin">
                                        <value>4</value>
                                        <min>2</min>
                                        <XRCED>
                                          <events>EVT_SPINCTRL</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                  </object>
                                  <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                  <border>2</border>
                                </object>
                                <orient>wxVERTICAL</orient>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                              <border>2</border>
                            </object>
                            <orient>wxVERTICAL</orient>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <label>Adaptive Kernel</label>
                      </object>
                      <size>200,-1d</size>
                      <XRCED>
                        <events>EVT_NOTEBOOK_PAGE_CHANGED</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxALL|wxEXPAND</flag>
                    <border>2</border>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND|wxALIGN_CENTRE</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxButton" name="CreateButton">
                      <label>Create</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                    <border>2</border>
                  </object>
                  <object class="spacer">
                    <size>30,-1d</size>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="CloseButton">
                      <label>Cancel</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                    <border>2</border>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                <border>5</border>
              </object>
              <orient>wxVERTICAL</orient>
              <XRCED>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>2</border>
          </object>
          <orient>wxVERTICAL</orient>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>2</border>
      </object>
      <orient>wxVERTICAL</orient>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <title>Weights Creation</title>
    <centered>1</centered>
    <style>wxCAPTION|wxSYSTEM_MENU|wxRESIZE_BORDER|wxRESIZE_BOX|wxCLOSE_BOX</style>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
  </object>
  <object class="wxFrame" name="mainGUI">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="ModelWeigths">
              <label>Create Model Weights...</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>35</border>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="KernelWeights">
              <label>Create Kernel Weights...</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>35</border>
          </object>
          <label>Create Weights</label>
          <orient>wxVERTICAL</orient>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <label>Weights Props</label>
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxButton" name="WeightsProps">
              <label>Open Weights Properties...</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>35</border>
          </object>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="Quit">
              <label>Quit</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_RIGHT</flag>
            <border>20</border>
          </object>
          <object class="spacer">
            <size>350,0</size>
          </object>
          <orient>wxVERTICAL</orient>
        </object>
        <flag>wxALL|wxALIGN_RIGHT</flag>
        <border>2</border>
      </object>
    </object>
    <title>GeoDa Weights -- Demo Application</title>
  </object>
  <object class="wxDialog" name="AddIDVar">
    <title>Add New ID Variable</title>
    <centered>1</centered>
    <style>wxDEFAULT_DIALOG_STYLE</style>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticText">
          <label>Enter new ID variable name:</label>
        </object>
        <flag>wxALL|wxALIGN_CENTRE</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxTextCtrl" name="idVarName">
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticText">
          <label>Existing Variables</label>
        </object>
        <flag>wxALL|wxALIGN_CENTRE</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxListBox" name="existingVarsListBox">
          <size>-1,190</size>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="save">
              <label>Save to DBF File</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>10</border>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="cancel">
              <label>Cancel</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>10</border>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxBOTTOM</flag>
        <border>5</border>
      </object>
    </object>
  </object>
  <object class="wxDialog" name="weightsProperties">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticText">
              <label>Select W:</label>
            </object>
            <flag>wxRIGHT</flag>
            <border>10</border>
          </object>
          <object class="sizeritem">
            <object class="wxChoice" name="selectWChoice">
              <size>350,-1</size>
              <XRCED>
                <events>EVT_CHOICE</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxALL|wxEXPAND|wxALIGN_CENTRE</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxFlexGridSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Name:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="nameTC">
                  <style>wxTE_READONLY</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND|wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Transform:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="transformChoice">
                  <XRCED>
                    <events>EVT_CHOICE</events>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxEXPAND|wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Islands:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="islandsTC">
                  <style>wxTE_READONLY</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxEXPAND|wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Neighbors of:</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="idListChoice">
                      <size>80,-1</size>
                      <XRCED>
                        <events>EVT_CHOICE</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                  </object>
                  <orient>wxVERTICAL</orient>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="weightsTC">
                  <size>-1,50</size>
                  <style>wxTE_MULTILINE|wxTE_READONLY</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Cardinalities:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="cardinalitiesTC">
                  <size>-1,50</size>
                  <style>wxTE_MULTILINE|wxTE_READONLY</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Ids:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="idsTC">
                  <size>-1,50</size>
                  <style>wxTE_MULTILINE|wxTE_READONLY</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Histogram:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="histogramTC">
                  <size>-1,50</size>
                  <tooltip>[(NumNeighbors, Count), ....]</tooltip>
                  <style>wxTE_MULTILINE|wxTE_READONLY</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Viewer:</label>
                </object>
                <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxButton" name="viewerButton">
                      <label>Launch...</label>
                      <font>
                        <size>13</size>
                        <style>normal</style>
                        <weight>normal</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Lucida Grande</face>
                        <encoding/>
                      </font>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>*Experimental</label>
                      <font>
                        <size>10</size>
                        <style>normal</style>
                        <weight>normal</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>applicationfont</face>
                        <encoding/>
                      </font>
                    </object>
                    <flag>wxLEFT|wxALIGN_BOTTOM</flag>
                    <border>5</border>
                  </object>
                </object>
              </object>
              <cols>2</cols>
              <rows>8</rows>
              <vgap>8</vgap>
              <hgap>5</hgap>
              <growablecols>1</growablecols>
              <growablerows>3,4,5,6</growablerows>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <label>Properties</label>
          <orient>wxVERTICAL</orient>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="closeButton">
              <label>Close</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL</flag>
            <border>10</border>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxALIGN_CENTRE</flag>
      </object>
    </object>
    <title>Weights Properties Editor</title>
    <style>wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER</style>
  </object>
</resource>'''

    ___regression_rc_list_add_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x00\x06bKGD\x00\x00\x00\x00\x00\x00\xf9C\xbb\x00\
\x00\x00\x09pHYs\x00\x00\x0d\xd7\x00\x00\x0d\xd7\x01B(\x9bx\x00\x00\x00\
\x07tIME\x07\xd6\x01\x0b\x10\x00\x11\x94Dx\xa1\x00\x00\x00\xd0IDAT8\xcb\
\xcd\x91\xbd\x0e\xc1`\x14\x86\x1f\xd2\xc5`\xb7r\x07\xd2\xba\x81\xc6`6[;\
tq\x07D\xd2\xc4d\x17\xb1Z\x0d&\x83\x84\x1b\xe8g7Z,Vi\xe2\xa7\xdf1\x10\x8a\
\xfa\x8b\x04\xefv\xf2\x9d\xbc\xf9\x9e\xe7\xc0\xaf\x93\xb8\xf7`9=\x1f0\x8f\
\xa3\xf2\xbb\x15+n/\xf9\xa0\xdc\xf4\\\x1b\xcf\xb5\x89\x14\xbdU\xf0R>.0\xee\
0\xc79\x91\xc8xrbD\x99[\xd5"[-$\x80mx\xde\xf7\\\x1b\x11\x109X\xafw\xc6\xe6\
\xcd\x0f\x00V\xeb\x90\xf92@\x04\xb4\x16\xb4@\xb0\x11\xc2P\xd8iAk\xc8eR\xf1\
\x08\x80jt&\x17\x08\xe5R\x01\x80\xc1\xc8\xbf&RO\xe5XNO\x86\xd3\x854\xfb\
3\xb9\xe2\xff\xf2\x19\xf3\xd9\xf4kg\x8c\x89\xaa\xb5O\xb6\x15\x9b=TrK\x0b\
\x8b\xb2w\x8e\x00\x00\x00\x00IEND\xaeB`\x82'''

    wx.MemoryFSHandler.AddFile('XRC/weights_view/weights_view_xrc', weights_view_xrc)
    wx.MemoryFSHandler.AddFile('XRC/weights_view/___regression_rc_list_add_png', ___regression_rc_list_add_png)
    __res.Load('memory:XRC/weights_view/weights_view_xrc')

