# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIALOGWEIGHTS(wx.Dialog):
#!XRCED:begin-block:xrcDIALOGWEIGHTS.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIALOGWEIGHTS.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOGWEIGHTS")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.InputPanel = xrc.XRCCTRL(self, "InputPanel")
        self.InputShapeChoice = xrc.XRCCTRL(self, "InputShapeChoice")
        self.OpenShape = xrc.XRCCTRL(self, "OpenShape")
        self.OutputPanel = xrc.XRCCTRL(self, "OutputPanel")
        self.OutputText = xrc.XRCCTRL(self, "OutputText")
        self.OpenOutput = xrc.XRCCTRL(self, "OpenOutput")
        self.IdvarChoice = xrc.XRCCTRL(self, "IdvarChoice")
        self.weightsNotebook = xrc.XRCCTRL(self, "weightsNotebook")
        self.ContiguityPanel = xrc.XRCCTRL(self, "ContiguityPanel")
        self.RadioQueen = xrc.XRCCTRL(self, "RadioQueen")
        self.ContiguityOrderSpin = xrc.XRCCTRL(self, "ContiguityOrderSpin")
        self.RadioRook = xrc.XRCCTRL(self, "RadioRook")
        self.ContiguityIncludeLowerCheck = xrc.XRCCTRL(self, "ContiguityIncludeLowerCheck")
        self.DistancePanel = xrc.XRCCTRL(self, "DistancePanel")
        self.ThresholdRadio = xrc.XRCCTRL(self, "ThresholdRadio")
        self.ThresholdSlider = xrc.XRCCTRL(self, "ThresholdSlider")
        self.CutoffText = xrc.XRCCTRL(self, "CutoffText")
        self.KnnRadio = xrc.XRCCTRL(self, "KnnRadio")
        self.NumNeighSpin = xrc.XRCCTRL(self, "NumNeighSpin")
        self.InverseRadio = xrc.XRCCTRL(self, "InverseRadio")
        self.PowerSpin = xrc.XRCCTRL(self, "PowerSpin")
        self.KernelPanel = xrc.XRCCTRL(self, "KernelPanel")
        self.KFuncChoice = xrc.XRCCTRL(self, "KFuncChoice")
        self.KNumNeighSpin = xrc.XRCCTRL(self, "KNumNeighSpin")
        self.CreateButton = xrc.XRCCTRL(self, "CreateButton")
        self.CloseButton = xrc.XRCCTRL(self, "CloseButton")

        self.Bind(wx.EVT_CHOICE, self.OnChoice_InputShapeChoice, self.InputShapeChoice)
        self.Bind(wx.EVT_BUTTON, self.OnButton_OpenShape, self.OpenShape)
        self.Bind(wx.EVT_TEXT, self.OnText_OutputText, self.OutputText)
        self.Bind(wx.EVT_BUTTON, self.OnButton_OpenOutput, self.OpenOutput)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_IdvarChoice, self.IdvarChoice)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_RadioQueen, self.RadioQueen)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_ContiguityOrderSpin, self.ContiguityOrderSpin)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_RadioRook, self.RadioRook)
        self.Bind(wx.EVT_CHECKBOX, self.OnCheckbox_ContiguityIncludeLowerCheck, self.ContiguityIncludeLowerCheck)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_ThresholdRadio, self.ThresholdRadio)
        self.Bind(wx.EVT_SCROLL, self.OnScroll_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_TOP, self.OnScroll_top_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_BOTTOM, self.OnScroll_bottom_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEUP, self.OnScroll_lineup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEDOWN, self.OnScroll_linedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEUP, self.OnScroll_pageup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEDOWN, self.OnScroll_pagedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBTRACK, self.OnScroll_thumbtrack_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBRELEASE, self.OnScroll_thumbrelease_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_CHANGED, self.OnScroll_changed_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL, self.OnScroll_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_TOP, self.OnScroll_top_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_BOTTOM, self.OnScroll_bottom_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEUP, self.OnScroll_lineup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_LINEDOWN, self.OnScroll_linedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEUP, self.OnScroll_pageup_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_PAGEDOWN, self.OnScroll_pagedown_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBTRACK, self.OnScroll_thumbtrack_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_THUMBRELEASE, self.OnScroll_thumbrelease_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_SCROLL_CHANGED, self.OnScroll_changed_ThresholdSlider, self.ThresholdSlider)
        self.Bind(wx.EVT_TEXT, self.OnText_CutoffText, self.CutoffText)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_KnnRadio, self.KnnRadio)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_NumNeighSpin, self.NumNeighSpin)
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_InverseRadio, self.InverseRadio)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_PowerSpin, self.PowerSpin)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_KFuncChoice, self.KFuncChoice)
        self.Bind(wx.EVT_SPINCTRL, self.OnSpinctrl_KNumNeighSpin, self.KNumNeighSpin)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnNotebook_page_changed_weightsNotebook, self.weightsNotebook)
        self.Bind(wx.EVT_BUTTON, self.OnButton_CreateButton, self.CreateButton)
        self.Bind(wx.EVT_BUTTON, self.OnButton_CloseButton, self.CloseButton)
        self.Bind(wx.EVT_CLOSE, self.OnClose)

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_InputShapeChoice
    def OnChoice_InputShapeChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_InputShapeChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_InputShapeChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_OpenShape
    def OnButton_OpenShape(self, evt):
        # Replace with event handler code
        print "OnButton_OpenShape()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_OpenShape        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnText_OutputText
    def OnText_OutputText(self, evt):
        # Replace with event handler code
        print "OnText_OutputText()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnText_OutputText        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_OpenOutput
    def OnButton_OpenOutput(self, evt):
        # Replace with event handler code
        print "OnButton_OpenOutput()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_OpenOutput        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_IdvarChoice
    def OnChoice_IdvarChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_IdvarChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_IdvarChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioQueen
    def OnRadiobutton_RadioQueen(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_RadioQueen()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioQueen        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_ContiguityOrderSpin
    def OnSpinctrl_ContiguityOrderSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_ContiguityOrderSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_ContiguityOrderSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioRook
    def OnRadiobutton_RadioRook(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_RadioRook()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_RadioRook        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnCheckbox_ContiguityIncludeLowerCheck
    def OnCheckbox_ContiguityIncludeLowerCheck(self, evt):
        # Replace with event handler code
        print "OnCheckbox_ContiguityIncludeLowerCheck()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnCheckbox_ContiguityIncludeLowerCheck        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_ThresholdRadio
    def OnRadiobutton_ThresholdRadio(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_ThresholdRadio()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_ThresholdRadio        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider
    def OnScroll_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider
    def OnScroll_top_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_top_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider
    def OnScroll_bottom_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_bottom_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider
    def OnScroll_lineup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_lineup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider
    def OnScroll_linedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_linedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider
    def OnScroll_pageup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pageup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider
    def OnScroll_pagedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pagedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider
    def OnScroll_thumbtrack_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbtrack_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider
    def OnScroll_thumbrelease_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbrelease_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider
    def OnScroll_changed_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_changed_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider
    def OnScroll_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider
    def OnScroll_top_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_top_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_top_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider
    def OnScroll_bottom_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_bottom_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_bottom_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider
    def OnScroll_lineup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_lineup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_lineup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider
    def OnScroll_linedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_linedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_linedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider
    def OnScroll_pageup_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pageup_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pageup_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider
    def OnScroll_pagedown_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_pagedown_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_pagedown_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider
    def OnScroll_thumbtrack_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbtrack_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbtrack_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider
    def OnScroll_thumbrelease_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_thumbrelease_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_thumbrelease_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider
    def OnScroll_changed_ThresholdSlider(self, evt):
        # Replace with event handler code
        print "OnScroll_changed_ThresholdSlider()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnScroll_changed_ThresholdSlider        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnText_CutoffText
    def OnText_CutoffText(self, evt):
        # Replace with event handler code
        print "OnText_CutoffText()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnText_CutoffText        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_KnnRadio
    def OnRadiobutton_KnnRadio(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_KnnRadio()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_KnnRadio        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_NumNeighSpin
    def OnSpinctrl_NumNeighSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_NumNeighSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_NumNeighSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnRadiobutton_InverseRadio
    def OnRadiobutton_InverseRadio(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_InverseRadio()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnRadiobutton_InverseRadio        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_PowerSpin
    def OnSpinctrl_PowerSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_PowerSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_PowerSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnChoice_KFuncChoice
    def OnChoice_KFuncChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_KFuncChoice()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnChoice_KFuncChoice        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnSpinctrl_KNumNeighSpin
    def OnSpinctrl_KNumNeighSpin(self, evt):
        # Replace with event handler code
        print "OnSpinctrl_KNumNeighSpin()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnSpinctrl_KNumNeighSpin        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnNotebook_page_changed_weightsNotebook
    def OnNotebook_page_changed_weightsNotebook(self, evt):
        # Replace with event handler code
        print "OnNotebook_page_changed_weightsNotebook()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnNotebook_page_changed_weightsNotebook        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_CreateButton
    def OnButton_CreateButton(self, evt):
        # Replace with event handler code
        print "OnButton_CreateButton()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_CreateButton        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnButton_CloseButton
    def OnButton_CloseButton(self, evt):
        # Replace with event handler code
        print "OnButton_CloseButton()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnButton_CloseButton        

#!XRCED:begin-block:xrcDIALOGWEIGHTS.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcDIALOGWEIGHTS.OnClose        


class xrcmainGUI(wx.Frame):
#!XRCED:begin-block:xrcmainGUI.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainGUI.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "mainGUI")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.ModelWeigths = xrc.XRCCTRL(self, "ModelWeigths")
        self.KernelWeights = xrc.XRCCTRL(self, "KernelWeights")
        self.Quit = xrc.XRCCTRL(self, "Quit")

        self.Bind(wx.EVT_BUTTON, self.OnButton_ModelWeigths, self.ModelWeigths)
        self.Bind(wx.EVT_BUTTON, self.OnButton_KernelWeights, self.KernelWeights)
        self.Bind(wx.EVT_BUTTON, self.OnButton_Quit, self.Quit)

#!XRCED:begin-block:xrcmainGUI.OnButton_ModelWeigths
    def OnButton_ModelWeigths(self, evt):
        # Replace with event handler code
        print "OnButton_ModelWeigths()"
#!XRCED:end-block:xrcmainGUI.OnButton_ModelWeigths        

#!XRCED:begin-block:xrcmainGUI.OnButton_KernelWeights
    def OnButton_KernelWeights(self, evt):
        # Replace with event handler code
        print "OnButton_KernelWeights()"
#!XRCED:end-block:xrcmainGUI.OnButton_KernelWeights        

#!XRCED:begin-block:xrcmainGUI.OnButton_Quit
    def OnButton_Quit(self, evt):
        # Replace with event handler code
        print "OnButton_Quit()"
#!XRCED:end-block:xrcmainGUI.OnButton_Quit        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    weights_view_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIALOGWEIGHTS">
    <object class="wxBoxSizer">
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxPanel" name="InputPanel">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <label>Input File</label>
                        <XRCED>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                    <object class="sizeritem">
                      <object class="wxChoice" name="InputShapeChoice">
                        <XRCED>
                          <events>EVT_CHOICE</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                      <border>5</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxBitmapButton" name="OpenShape">
                        <bitmap stock_id="wxART_FILE_OPEN"/>
                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_RIGHT</flag>
                    </object>
                  </object>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_HORIZONTAL</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxPanel" name="OutputPanel">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <label>Save output as</label>
                        <XRCED>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                    <object class="sizeritem">
                      <object class="wxTextCtrl" name="OutputText">
                        <style>wxTE_READONLY</style>
                        <XRCED>
                          <events>EVT_TEXT</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                      <border>5</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxBitmapButton" name="OpenOutput">
                        <bitmap stock_id="wxART_FILE_SAVE"/>
                        <style>wxBU_AUTODRAW|wxBU_EXACTFIT</style>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                  </object>
                  <enabled>0</enabled>
                  <hidden>1</hidden>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_HORIZONTAL</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Select an ID variable for the weights file</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
                    <border>2</border>
                  </object>
                  <object class="spacer">
                    <size>3,5d</size>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>2</border>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="IdvarChoice">
                      <XRCED>
                        <events>EVT_CHOICE</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxALL|wxALIGN_CENTRE</flag>
                    <border>2</border>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxEXPAND</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxNotebook" name="weightsNotebook">
                      <object class="notebookpage">
                        <object class="wxPanel" name="ContiguityPanel">
                          <object class="wxBoxSizer">
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxFlexGridSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="RadioQueen">
                                        <label>Queen</label>
                                        <value>1</value>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>25,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <label>Order of contiguity</label>
                                            <XRCED>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSpinCtrl" name="ContiguityOrderSpin">
                                            <value>1</value>
                                            <min>1</min>
                                            <XRCED>
                                              <events>EVT_SPINCTRL</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="RadioRook">
                                        <label>Rook</label>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>25,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="sizeritem">
                                          <object class="wxCheckBox" name="ContiguityIncludeLowerCheck">
                                            <label>Include lower orders</label>
                                            <XRCED>
                                              <events>EVT_CHECKBOX</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                      </object>
                                    </object>
                                    <cols>3</cols>
                                    <rows>2</rows>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                                  <border>2</border>
                                </object>
                                <orient>wxHORIZONTAL</orient>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                              <border>2</border>
                            </object>
                            <orient>wxVERTICAL</orient>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <label>Contiguity</label>
                        <selected>1</selected>
                      </object>
                      <object class="notebookpage">
                        <object class="wxPanel" name="DistancePanel">
                          <object class="wxBoxSizer">
                            <orient>wxVERTICAL</orient>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="ThresholdRadio">
                                        <label>Threshold Distance</label>
                                        <value>1</value>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="spacer">
                                          <size>25,5d</size>
                                          <flag>wxLEFT|wxALL</flag>
                                          <XRCED>
                                            <assign_var>1</assign_var>
                                          </XRCED>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSlider" name="ThresholdSlider">
                                            <size>150,-1d</size>
                                            <value>0</value>
                                            <min>0</min>
                                            <max>100000</max>
                                            <style>wxSL_HORIZONTAL</style>
                                            <XRCED>
                                              <events>EVT_SCROLL|EVT_SCROLL_TOP|EVT_SCROLL_BOTTOM|EVT_SCROLL_LINEUP|EVT_SCROLL_LINEDOWN|EVT_SCROLL_PAGEUP|EVT_SCROLL_PAGEDOWN|EVT_SCROLL_THUMBTRACK|EVT_SCROLL_THUMBRELEASE|EVT_SCROLL_CHANGED|EVT_SCROLL|EVT_SCROLL_TOP|EVT_SCROLL_BOTTOM|EVT_SCROLL_LINEUP|EVT_SCROLL_LINEDOWN|EVT_SCROLL_PAGEUP|EVT_SCROLL_PAGEDOWN|EVT_SCROLL_THUMBTRACK|EVT_SCROLL_THUMBRELEASE|EVT_SCROLL_CHANGED</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                                          <border>2</border>
                                        </object>
                                      </object>
                                      <flag>wxLEFT|wxALL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <object class="spacer">
                                          <size>25,5d</size>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <label>Cut-off point</label>
                                          </object>
                                          <flag>wxLEFT|wxALL|wxADJUST_MINSIZE</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxTextCtrl" name="CutoffText">
                                            <style>wxTE_RIGHT</style>
                                            <XRCED>
                                              <events>EVT_TEXT</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                          <flag>wxLEFT|wxRIGHT</flag>
                                          <border>5</border>
                                        </object>
                                      </object>
                                    </object>
                                    <orient>wxVERTICAL</orient>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxLEFT|wxALL</flag>
                                  <border>2</border>
                                </object>
                                <object class="spacer">
                                  <size>3,3d</size>
                                  <XRCED>
                                    <assign_var>1</assign_var>
                                  </XRCED>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="KnnRadio">
                                        <size>80,-1d</size>
                                        <label>k-Nearest Neighbors</label>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>5,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <size>50,-1d</size>
                                            <label># of neighbors</label>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSpinCtrl" name="NumNeighSpin">
                                            <size>45,-1d</size>
                                            <value>4</value>
                                            <min>2</min>
                                            <XRCED>
                                              <events>EVT_SPINCTRL</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                        </object>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>2</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxRadioButton" name="InverseRadio">
                                        <size>80,-1d</size>
                                        <label>Inverse Distance</label>
                                        <XRCED>
                                          <events>EVT_RADIOBUTTON</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>5,5d</size>
                                      <XRCED>
                                        <assign_var>1</assign_var>
                                      </XRCED>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxBoxSizer">
                                        <orient>wxHORIZONTAL</orient>
                                        <XRCED>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                        <object class="sizeritem">
                                          <object class="wxStaticText">
                                            <size>50,-1d</size>
                                            <label>Power</label>
                                          </object>
                                          <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                          <border>2</border>
                                        </object>
                                        <object class="sizeritem">
                                          <object class="wxSpinCtrl" name="PowerSpin">
                                            <size>45,-1d</size>
                                            <value>1</value>
                                            <min>1</min>
                                            <XRCED>
                                              <events>EVT_SPINCTRL</events>
                                              <assign_var>1</assign_var>
                                            </XRCED>
                                          </object>
                                        </object>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                    <XRCED>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>2</border>
                                </object>
                                <orient>wxVERTICAL</orient>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                              <border>2</border>
                            </object>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <label>Distance</label>
                      </object>
                      <object class="notebookpage">
                        <object class="wxPanel" name="KernelPanel">
                          <object class="wxBoxSizer">
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxStaticText">
                                        <size>50,-1d</size>
                                        <label>Kernel function</label>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxChoice" name="KFuncChoice">
                                        <content>
                                          <item>Uniform</item>
                                          <item>Triangular</item>
                                          <item>Epanechnikov</item>
                                          <item>Quartic</item>
                                          <item>Gaussian</item>
                                        </content>
                                        <selection>0</selection>
                                        <XRCED>
                                          <events>EVT_CHOICE</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                      <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="spacer">
                                      <size>30,-1d</size>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                  </object>
                                  <flag>wxTOP|wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                  <border>2</border>
                                </object>
                                <object class="spacer">
                                  <size>2,2d</size>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBoxSizer">
                                    <object class="sizeritem">
                                      <object class="wxStaticText">
                                        <size>50,-1d</size>
                                        <label># of neighbors</label>
                                      </object>
                                      <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                      <border>2</border>
                                    </object>
                                    <object class="sizeritem">
                                      <object class="wxSpinCtrl" name="KNumNeighSpin">
                                        <value>4</value>
                                        <min>2</min>
                                        <XRCED>
                                          <events>EVT_SPINCTRL</events>
                                          <assign_var>1</assign_var>
                                        </XRCED>
                                      </object>
                                    </object>
                                    <orient>wxHORIZONTAL</orient>
                                  </object>
                                  <flag>wxLEFT|wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                                  <border>2</border>
                                </object>
                                <orient>wxVERTICAL</orient>
                                <XRCED>
                                  <assign_var>1</assign_var>
                                </XRCED>
                              </object>
                              <flag>wxALL|wxALIGN_CENTRE_HORIZONTAL</flag>
                              <border>2</border>
                            </object>
                            <orient>wxVERTICAL</orient>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                          </object>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <label>Adaptive Kernel</label>
                      </object>
                      <size>200,-1d</size>
                      <XRCED>
                        <events>EVT_NOTEBOOK_PAGE_CHANGED</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxALL|wxEXPAND</flag>
                    <border>2</border>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND|wxALIGN_CENTRE</flag>
                <border>2</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxButton" name="CreateButton">
                      <label>Create</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                    <border>2</border>
                  </object>
                  <object class="spacer">
                    <size>30,-1d</size>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="CloseButton">
                      <label>Cancel</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                    <border>2</border>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxALL|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                <border>5</border>
              </object>
              <orient>wxVERTICAL</orient>
              <XRCED>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>2</border>
          </object>
          <orient>wxVERTICAL</orient>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>2</border>
      </object>
      <orient>wxVERTICAL</orient>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <title>Weights Creation</title>
    <centered>1</centered>
    <style>wxCAPTION|wxSYSTEM_MENU|wxRESIZE_BORDER|wxRESIZE_BOX|wxCLOSE_BOX</style>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
  </object>
  <object class="wxFrame" name="mainGUI">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="ModelWeigths">
              <label>Create Model Weights...</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>35</border>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="KernelWeights">
              <label>Create Kernel Weights...</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>35</border>
          </object>
          <label>Create Weights</label>
          <orient>wxVERTICAL</orient>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>10</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="Quit">
              <label>Quit</label>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <flag>wxALL|wxALIGN_RIGHT</flag>
            <border>20</border>
          </object>
          <orient>wxVERTICAL</orient>
          <object class="spacer">
            <size>350,0</size>
          </object>
        </object>
        <flag>wxALL|wxALIGN_RIGHT</flag>
      </object>
    </object>
    <title>GeoDa Weights -- Demo Application</title>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/weights_view/weights_view_xrc', weights_view_xrc)
    __res.Load('memory:XRC/weights_view/weights_view_xrc')

