#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

GeoDa = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAapJ"
    "REFUOI2lkr1rU1EYxn/PSaMd/LrUr9IoNFnERRyERnCooG4u/gG6FDdxcHFxEEehm2Nx7eLY"
    "v0AoKNW1YhLrB8QqV63NNQlJ7uNw02piqF/v9HI47/P+znMeKeT4nxr704vvbk5YGjybmo/1"
    "W4FHNfno83H0GFKbTENI3pkgVzvjg25zfGmNyUoeBEHC/BABCCOHl5/5UrfHwusXTFbzWGCM"
    "bTDYZP0wQTFUHd9epnHkOmf9ksJqHmysbJ8zeH72YoCgccE0ri5SdsxJbVK5mNDclxKyxQRt"
    "yQwJFEPF06Hi5PIK5Op89i7qHgeZ96dbxKVOXyQFtI0PEIqhYgO9Q6JV/grAatjLAsewYf1U"
    "m7Fmn9mA3H/CtolCQKdg3JqFD4uwMcd6OsETRQizdj6hvcdA6HshpuZjAYRaWsqaTTh8C9wx"
    "bsxQz3V5wDQrPkASpbwtf6MVdXkz06TQHwbQVpSLoWpjvszBxjWh/fdh91MAbvCKc4qxxZWS"
    "B/L4i4AQyaz5eE8ouguI3omHQyEe8Y21tCQhDPQiUAJ8urPj8ADBv9bIKP9NfQeoVbJivS0J"
    "EQAAAABJRU5ErkJggg==")
getGeoDaData = GeoDa.GetData
getGeoDaImage = GeoDa.GetImage
getGeoDaBitmap = GeoDa.GetBitmap
getGeoDaIcon = GeoDa.GetIcon

