# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcTextWindow(wx.Frame):
#!XRCED:begin-block:xrcTextWindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcTextWindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "TextWindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.ToolBar = xrc.XRCCTRL(self, "ToolBar")
        self.Panel = xrc.XRCCTRL(self, "Panel")
        self.Text = xrc.XRCCTRL(self, "Text")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    textwindow_view_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="TextWindow">
    <title>Results</title>
    <object class="wxToolBar" name="ToolBar">
      <object class="tool" name="ToolNew">
        <bitmap stock_id="wxART_NEW"/>
        <tooltip>Create A New Results File...</tooltip>
      </object>
      <object class="tool" name="ToolOpen">
        <bitmap stock_id="wxART_FILE_OPEN"/>
        <tooltip>Open Results File...</tooltip>
      </object>
      <object class="tool" name="ToolSave">
        <bitmap stock_id="wxART_FILE_SAVE"/>
        <tooltip>Save Results File</tooltip>
      </object>
      <object class="tool" name="ToolSaveAs">
        <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        <tooltip>Save Results File As...</tooltip>
      </object>
      <object class="separator"/>
      <object class="tool" name="ToolFontSmaller">
        <bitmap>___icons_list_remove_png</bitmap>
        <tooltip>Decrease Font Size</tooltip>
        <label>TOOL</label>
      </object>
      <object class="tool" name="ToolFontBigger">
        <bitmap>___icons_list_add_png</bitmap>
        <tooltip>Increase Font Size</tooltip>
        <label>TOOL</label>
      </object>
      <style>wxTB_FLAT|wxTB_HORIZONTAL</style>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxPanel" name="Panel">
          <object class="wxBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxTextCtrl" name="Text">
                <size>700,300</size>
                <font>
                  <size>10</size>
                  <style>normal</style>
                  <weight>normal</weight>
                  <underlined>0</underlined>
                  <family>default</family>
                  <face>Courier New</face>
                </font>
                <style>wxTE_MULTILINE|wxTE_READONLY|wxTE_LINEWRAP</style>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>1</option>
              <flag>wxALL|wxEXPAND|wxADJUST_MINSIZE</flag>
            </object>
          </object>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
      </object>
    </object>
  </object>
</resource>'''

    ___icons_list_remove_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x00\x06bKGD\x00\x00\x00\x00\x00\x00\xf9C\xbb\x00\
\x00\x00\x09pHYs\x00\x00\x0d\xd7\x00\x00\x0d\xd7\x01B(\x9bx\x00\x00\x00\
\x07tIME\x07\xd6\x01\x0b\x0f;"\x00\\\x12\xc2\x00\x00\x00\x84IDAT8\xcb\xed\
\x91\xb1\x09\x83P\x10\x86\xbf\x07i\xdc\xc0:+\xe8\x08\x19#\xadmF\x08\x19\
 \x0b\x88\xads\xc4\x05t\x88\xd4\xb6"D\xf3\xeeO!\xca\xb3\xb33\x85\x1f\x1c\
\x1c\x07\xffw\x1c\x07\x07\xfb\xe3\xe6&\xcd\xca\x1aH6\xe6\x9a\xba\xb8\xa6\
\x00\xa7`\x98<o\x17F\x13\x0e\x18\xbdV\x09i*\x07\xdc\xf3\xd7\xb2(\x14\xd0\
}<\xef\xb6G\x023a\x82~\x10\xde\x8b\xaf\x0938\xc7\xd1J\x1c
\x9aG^m>\xe1\xf8\xfe?\xf1\x03\xacS-\xdbF\xe4\x80\xd8\x00\x00\x00\x00IE\
ND\xaeB`\x82'''

    ___icons_list_add_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x00\x06bKGD\x00\x00\x00\x00\x00\x00\xf9C\xbb\x00\
\x00\x00\x09pHYs\x00\x00\x0d\xd7\x00\x00\x0d\xd7\x01B(\x9bx\x00\x00\x00\
\x07tIME\x07\xd6\x01\x0b\x10\x00\x11\x94Dx\xa1\x00\x00\x00\xd0IDAT8\xcb\
\xcd\x91\xbd\x0e\xc1`\x14\x86\x1f\xd2\xc5`\xb7r\x07\xd2\xba\x81\xc6`6[;\
tq\x07D\xd2\xc4d\x17\xb1Z\x0d&\x83\x84\x1b\xe8g7Z,Vi\xe2\xa7\xdf1\x10\x8a\
\xfa\x8b\x04\xefv\xf2\x9d\xbc\xf9\x9e\xe7\xc0\xaf\x93\xb8\xf7`9=\x1f0\x8f\
\xa3\xf2\xbb\x15+n/\xf9\xa0\xdc\xf4\\\x1b\xcf\xb5\x89\x14\xbdU\xf0R>.0\xee\
0\xc79\x91\xc8xrbD\x99[\xd5"[-$\x80mx\xde\xf7\\\x1b\x11\x109X\xafw\xc6\xe6\
\xcd\x0f\x00V\xeb\x90\xf92@\x04\xb4\x16\xb4@\xb0\x11\xc2P\xd8iAk\xc8eR\xf1\
\x08\x80jt&\x17\x08\xe5R\x01\x80\xc1\xc8\xbf&RO\xe5XNO\x86\xd3\x854\xfb\
3\xb9\xe2\xff\xf2\x19\xf3\xd9\xf4kg\x8c\x89\xaa\xb5O\xb6\x15\x9b=TrK\x0b\
\x8b\xb2w\x8e\x00\x00\x00\x00IEND\xaeB`\x82'''

    wx.MemoryFSHandler.AddFile('XRC/textwindow_view/textwindow_view_xrc', textwindow_view_xrc)
    wx.MemoryFSHandler.AddFile('XRC/textwindow_view/___icons_list_remove_png', ___icons_list_remove_png)
    wx.MemoryFSHandler.AddFile('XRC/textwindow_view/___icons_list_add_png', ___icons_list_add_png)
    __res.Load('memory:XRC/textwindow_view/textwindow_view_xrc')

